### ISSUE TITLE
Effects on Map Control?

### ISSUE THREAD

**Issue by nesherhh** [Microsoft/WindowsUIDevLabs#100]
Is it possible to add effects to map control?

**Comment by robmikh** [comment]
There's two routes you can take when you want to apply an effect to a XAML control. The first is to create an image of the control to manipulate with the Composition API using [RenderTargetBitmap](https://msdn.microsoft.com/library/windows/apps/xaml/windows.ui.xaml.media.imaging.rendertargetbitmap.aspx). The issue with this approach is that it's not a "live" effect, because it is only a snapshot of the control.

For something like the Maps control you would want to do it with the BackdropBrush. You would build your effect brush normally, but when it comes time to setting the source of your effect to some ComposiitonSurfaceBrush, you would instead set it to a CompositionBackdropBrush. What the BackdropBrush does is take everything behind the visual its attached to. So if you have part of a Button and an Image control behind a visual, it will apply the effect to that entire area. You can use this to apply an effect to the Maps control.

Here's a snippet that applies an effect to a given control:

```
private void ApplyEffectToControl(
    UIElement control, 
    CompositionEffectBrush effectBrush, 
    String sourceParameterName)
{
    // Get our Compositor object.
    var compositor = effectBrush.Compositor;

    // Get the visual that represents our control
    var controlVisual = ElementCompositionPreview.GetElementVisual(control);

    // Create the visual that will house the effect. In order for the BackdropBrush
    // to work correctly, we'll need to apply a size to our visual that matches the
    // size of our control. Starting in the Anniversary Update, visuals retreived from
    // GetElementVisual will actually have their correct size information. To keep
    // the two in sync with eachother, we'll apply an expression to our visual to match
    // the size of the visual of the control.
    var visual = compositor.CreateSpriteVisual();
    visual.Size = controlVisual.Size;
    var expression = compositor.CreateExpressionAnimation();
    expression.Expression = "visual.Size";
    expression.SetReferenceParameter("visual", controlVisual);
    visual.StartAnimation(nameof(Visual.Size), expression);

    // Next we create our BackdropBrush and apply it as the input to the effect brush
    // we've been given. Since you can arbitrarily define the name of the effect input
    // we have gotten that from the caller in the sourceParamterName parameter.
    var backdropBrush = compositor.CreateBackdropBrush();
    effectBrush.SetSourceParameter(sourceParameterName, backdropBrush);
    visual.Brush = effectBrush;

    // Now in order for this to work properly, our new visual needs to be inserted in the
    // tree such that it is drawn on top of our control. Luckily for us, when you add a 
    // visual as a child it will be drawn "after" its parent and thus be "on top". So all
    // we have to do is add the visual as a child of our control.
    ElementCompositionPreview.SetElementChildVisual(control, visual);
}
```

This is a great solution if you're only applying an effect to one control. If you'd like to apply this effect more broadly, I would think about trying to cover everything with your one visual instead of having many individual ones. You could also write a control that does the same thing. We have one in [SamplesCommon](https://github.com/Microsoft/WindowsUIDevLabs/tree/master/SamplesCommon/SamplesCommon) that you can take a look at called the [BackDrop](https://github.com/Microsoft/WindowsUIDevLabs/blob/master/SamplesCommon/SamplesCommon/BackDrop.cs) control.

**Comment by pgills** [comment]
Closing please reopen if there are any other more issues discovered.
