### ISSUE TITLE
Animating CompositionPropertySet values

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#107]
I have a sample UWP application in which the MainPage contains a **CanvasAnimatedControl** (from **Win2d**) and a button. I have two **CompositionPropertySets** - **propSet** containing a scalar **Angle** and **animPropSet** containing a scalar **RotationAngle**. 
Now, whenever the value of the scalar **Angle** changes, I need to animate the scalar **RotationAngle** to that value.

Here is the code
```C#
Random random = new Random();
CompositionPropertySet propSet;
CompositionPropertySet animPropSet;

private void MainPage_Loaded(object sender, RoutedEventArgs e)
{
    propSet = _compositor.CreatePropertySet();
    propSet.InsertScalar("Angle", 0f);

    var angleAnimation = _compositor.CreateScalarKeyFrameAnimation();
    angleAnimation.InsertExpressionKeyFrame(1f, "props.Angle");
    angleAnimation.SetReferenceParameter("props", propSet);
    angleAnimation.Duration = TimeSpan.FromMilliseconds(1000);

    animPropSet = _compositor.CreatePropertySet();
    animPropSet.InsertScalar("RotationAngle", 0f);

    animPropSet.StartAnimation("RotationAngle", angleAnimation);
}

private async void AnimatedCanvasCtrl_OnDraw(ICanvasAnimatedControl sender, CanvasAnimatedDrawEventArgs args)
{
    var angle = 0f;
    animPropSet.TryGetScalar("RotationAngle", out angle);
}

private void Button_OnClick(object sender, RoutedEventArgs e)
{
    var finalvalue = (float)(random.Next(60, 190) % 360);

    propSet.InsertScalar("Angle", finalvalue);
}
```
Whenever the button is clicked, the value of the scalar **Angle** changes to a random value. But the value of the scalar **RotationAngle** does not change.

Also, _since the **AnimatedCanvasCtrl_OnDraw** method gets called 60 times per second_, I was hoping that calling the **TryGetScalar** method on **animPropSet** will give me the intermediate values of the animation. But this is also not happening.

I am trying to avoid writing my own algorithm for animating from one value to another and reuse the animation logic provided in Composition to get the intermediate animation values.

It would be great if you could tell me if this is possible or do I have to implement my own animation logic.

**Comment by patsiu** [comment]
Hey @ratishphilip, sorry for the late reply, but let me try answer your question(s): 

To start, you are correct that based on the above code, the value of RotationAngle will not change to the new value of Angle on each button click. This is because you called StartAnimation for your KeyFrame Animation on RotationAngle when the main page loads. This means that when the main page loads, the animation gets run for a 1 second duration and then stops. Thus afterwards when the button is clicked, there is no active animation on RotationAngle. You have a couple of options:
- If you want to use KeyFrame Animations, instead of calling StartAnimation when the main page loads, call it when the value of angle changes (probably on the button click event).
- Instead of attaching a KeyFrameAnimation to RotationAngle, attach an ExpressionAnimation. Note that with this model, the value of RotationAngle will change "instantly" to the new value instead of interpolating to new over the 1 second duration that you get with KeyFrames. However, ExpressionAnimations don't stop, so once you start it on RotationAngle, it will always change to the value calculated by the Expression. In this case the Expression would be the same as the content in the ExpressionKeyFrame.

To your other question about querying the value of RotationAngle. If the value of RotationAngle is currently being animated, the value will not be updated until that animation completes - so you will not be able to query the intermediate values. The best way to know when to query the value when the animation completes is to put the KeyFrame Animation in a batch and listen for the BatchComplete events. When that event fires, query the value of RotationAngle.

Hope this helps!

**Comment by ratishphilip** [comment]
@patsiu 
Thanks for the reply.
The only goal for this entire code was to **obtain the intermediate values of a Scalar, _which is being animated_, during the animation.** :)

I just wanted to know if it was possible to harness the internal animation engine of Composition to generate the intermediate values for me, so that I can use them in my calculations, instead of writing my own animation logic.

It seems that now I have to implement my own animation logic.

**Comment by patsiu** [comment]
@ratishphilip ok thanks for clarifying. Our team has talked about different ways for developers to obtain the intermediate values of animating properties, but there are some perf implications to most of the models. We're continuing to explore this problem, but unfortunately won't have anything in the short term.

**Comment by ratishphilip** [comment]
@patsiu 
Hope to see some great solution to this in the near future.
Thanks.
