### ISSUE TITLE
Getting values from animations or spritevisual not working

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#111]
I have created an orbital animation that works:

           #region Animation
            string x = "propertySet.Translate + cos(propertySet.Rotation) * propertySet.Radius";
            string y = "propertySet.Translate + sin(propertySet.Rotation) * propertySet.Radius";
            ExpressionAnimation expressionAnimation = compositor.CreateExpressionAnimation($"Vector3({x},{y},0)");

            propertySet = compositor.CreatePropertySet();
            propertySet.InsertScalar("Rotation", 0f);
            propertySet.InsertScalar("Radius", 100f);
            propertySet.InsertScalar("Translate", 140f);

            expressionAnimation.SetReferenceParameter("propertySet", propertySet);

            ellipseVisual.StartAnimation("Offset", expressionAnimation);

            var linear = compositor.CreateLinearEasingFunction();
            var rotAnimation = compositor.CreateScalarKeyFrameAnimation();
            rotAnimation.InsertKeyFrame(1.0f, 6.2831853f, linear);
            rotAnimation.Duration = TimeSpan.FromMilliseconds(20000);
            rotAnimation.IterationBehavior = AnimationIterationBehavior.Forever;
            propertySet.StartAnimation("Rotation", rotAnimation);
            #endregion  

Now what I want is to get from time to time the value of the ellipseVisual offset, so the first thing I thought is with a DispatcherTimer grab the spriteVisual.Offset property (which is the one I am animating) but it returns always the Zero Vector3.

So I tried another option, getting the Rotation angle and then convert, but also the same issue:

       private void InitializeAudioTimer()
        {
            AudioTimer = new DispatcherTimer()
            {
                Interval = TimeSpan.FromSeconds(0.5)
            };

            AudioTimer.Tick += (s, e) =>
            {
                if (propertySet == null)
                    return;

                float angle = 0f;
                if(propertySet.TryGetScalar("Rotation", out angle) == CompositionGetValueStatus.Succeeded)
                {
                    var pos = new Vector3((float)Math.Cos(angle), (float)Math.Sin(angle), 0);
                    PositionChanged?.Invoke(pos);
                }
            };

            AudioTimer.Start();
        }

In this case the angle is always zero and the CompositionGetValueStatus is Succeeded.

So what am I doing wrong, that I cannot get the values?

**Comment by ratishphilip** [comment]
Hi @juanpaexpedite 
It seems that you want to obtain the intermediate values of the Offset/Rotation during animation.
I had a similar requirement and had raised a similar question ( #107 )
As of now Composition does not provide any method through which you can obtain the intermediate values (due to perf implications). You can write your own animation logic and obtain the intermediate values.

**Comment by juanpaexpedite** [comment]
Exactly, thank you for the link, I always look another issues, but only the opened. 

I understand performance is one of the basis of Composition and implementing this could be get us back to having low perf dependency objects. I will use the Thread timer to make the animation and test the result. 

Meanwhile writing I remembered there is an pre-composition static event: CompositionTarget.Render (might be was the first Composition thing accessible) that could be interesting also to test.

**Comment by ratishphilip** [comment]
@juanpaexpedite 
You can also use Win2D's **CanvasAnimatedControl**. The Draw method is called 60 times per second by default and is independent of the UI thread.

**Comment by juanpaexpedite** [comment]
yes thank you, I will try to not make it too complex,

**Comment by juanpaexpedite** [comment]
Just for the record, I tested both DispatcherTimer and Thread.Timer and the second one works really smooth and I can inject the parameter to the   propertySet.InsertScalar("Rotation", i); without issues, so let's continue by this way.

**Comment by robmikh** [comment]
Just for future reference, the reason why using the `System.Threading.Timer` is smoother than the `DispatchTimer` is because of what threads these two objects operate on.

The `DispatchTimer` will queue work on the UI thread using the `Dispatcher`. This means that if you have a lot of work going on on the UI thread, it might take awhile to get to your queued work. Using this timer is really great if you want to manipulate XAML objects, or other objects that can only be manipulated on the UI thread. To learn more, check out this [MSDN article](https://msdn.microsoft.com/library/windows/apps/windows.ui.xaml.dispatchertimer.aspx).

Because Compososition objects can be manipulated off the UI thread, you should usually use the `System.Threading.Timer` version. This timer spins up a worker thread that will do the work you specify. However, you should be careful with this timer! Unlike the `DispatchTimer`, which will only ever call your code on the UI thread sequentially, the threading version of the timer will call your callback at the interval every time. If your code is still running when the next interval happens, your code will be called again, which can cause reentrancy issues. If you want to protect yourself against that, you can use the pattern I mentioned in [this question](https://github.com/Microsoft/WindowsUIDevLabs/issues/34).

**Comment by ratishphilip** [comment]
@robmikh I have a doubt regarding the pattern which you mentioned in #34.
What if the Game code within the GameLoop() takes more than TIME_INTERVAL_IN_MILLISECONDS to execute?

**Comment by robmikh** [comment]
So the assumption is that if you went over the allotted time, you would want to schedule your next pass immediately. To do that, you do `Math.Max(0, TIME_INTERVAL_IN_MILLISECONDS - stopwatch.ElapsedMilliseconds)`, which will yield 0 if you take longer than the established interval and fire the callback immediately.

With that said, if you care about vsyncs, you shouldn't use a timer, as you are never guaranteed to start the timer at the beginning of a vsync. Instead you should wait for the panel's clock using a real wait for vsync.

**Comment by juanpaexpedite** [comment]
I think even that the Timer was not available long time ago and is back. I made a base class based on your @robmikh great idea, [CompositionTimer](https://github.com/juanpaexpedite/MasterDetailsComposition/blob/master/UniversalComposition/CompositionTimer.cs) it just the basis, but it's great to do not crash the app :). 

Thank you, now I have a Composition animation with the geometry blur on there and over an animation with this timer, imho really stunning, I'll share it soon, just to say that it's 'just' to set the rotation angle to use in a composition expression and in the audiograph emitter both really new and awesome APIs.
