### ISSUE TITLE
Setting "SingleSelectionFollowsFocus" property casues compiler error.

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/WindowsUIDevLabs#121]
Basically a simple bug that's existed for a while, but is still present on the 14388 SDK: setting "SingleSelectionFollowsFocus" property in XAML causes:

> XamlCompiler error WMC0610: XBF generation error code 0x09c4.

For example: 
`<ListBox SingleSelectionFollowsFocus="True" />`

**Comment by JohnnyWestlake** [comment]
Setting it to true from code behind doesn't crash, but it certainly doesn't seem to do what it suggests either - at least when using the gamepad.

**Comment by pgills** [comment]
@JohnnyWestlake Thanks. I'll forward this over to framework team.

**Comment by JasterAtMicrosoft** [comment]
For anyone still interested in this, this error happens when the Min Version for your project doesn't support the API you are using in markup. It looks like the error in Visual Studio has been updated to clarify this.

Some more info about supporting multiple versions here: [link](https://msdn.microsoft.com/en-us/windows/uwp/debug-test-perf/version-adaptive-code).
