### ISSUE TITLE
Applying an alpha mask to a list/grid control

### ISSUE THREAD

**Issue by darenm** [Microsoft/WindowsUIDevLabs#128]
Hey all - I asked this question on StackOverflow - is there an approach I have missed to achieving this effect:

[UWP Composition - Apply opacity mask to top 30px of a ListView](http://stackoverflow.com/questions/38361081/uwp-composition-apply-opacity-mask-to-top-30px-of-a-listview/38369502?noredirect=1#comment64186730_38369502)

<a href="http://i.stack.imgur.com/LpOu0.gif">![alt text][1]</a>
[1]: http://i.stack.imgur.com/LpOu0.gif

**Comment by sohchatt** [comment]
It seems like you want a 30px gradient mask on top of your ListView with the condition that the content being masked is the same image as that used for the ListView's background. Do correct me if my understanding of your issue is incorrect. 

Now, assuming that I understood your problem correctly, here's a possible solution:

You can paint a SpriteVisual of the appropriate size with a MaskBrush whose Mask is a SurfaceBrush with gradient opacity mask and whose Source is a SurfaceBrush with your desired background image. It is worth calling out that you can control the Stretch property of the SurfaceBrushes to suit your needs. 
I'm assuming that you've loaded your assets (say backgroundImage.png and gradientMask.png) onto ICompositionSurfaces (using SurfaceLoader in SamplesCommon or RobMikh's CompositionImageLoader, etc.). Let's say that we now have two ICompositionSurfaces called backgroundImageSurface and gradientMaskSurface. Then:


       `   // create surfacebrush with ICompositionSurface that contains the background image to be masked
            CompositionSurfaceBrush backgroundImageBrush = _compositor.CreateSurfaceBrush(backgroudImageSurface);
            backgroundImageBrush.Stretch = CompositionStretch.Fill;

            // create surfacebrush with ICompositionSurface that contains the gradient opacity mask asset
            CompositionSurfaceBrush opacityBrush = _compositor.CreateSurfaceBrush(gradientMaskSurface);
            opacityBrush.Stretch = CompositionStretch.Fill;

            // create maskbrush
            CompositionMaskBrush maskbrush = _compositor.CreateMaskBrush();
            maskbrush.Mask = opacityBrush; // surfacebrush with gradient opacity mask asset
            maskbrush.Source = backgroundImageBrush; // surfacebrush with background image that is to be masked

            // create spritevisual of the approproate size, offset, etc.
            SpriteVisual maskSprite = _compositor.CreateSpriteVisual();
            maskSprite.Size = new Vector2( (float) ListViewGrid.ActualWidth, 30);
            maskSprite.Brush = maskbrush; // paint it with the maskbrush

            // set the sprite visual as a child of the XAML element it needs to be drawn on top of
            ElementCompositionPreview.SetElementChildVisual(ListViewGrid, maskSprite);`


Note that CompositionMaskBrush is a new brush type introduced in the anniversary release that provides a way of alpha-masking its Source by the specified Mask. The MaskBrush itself cannot be set as Source to an EffectBrush. So, if you now wanted to apply any additional effects to the content of maskSprite, MaskBrush would not be the right solution for you. You would essentially do the same thing, but use an CompositionEffectBrush and use the Composite effect to alpha-mask backgroundImageBrush with opacityBrush, then chain the results with your desired effects. 

I hope this helps.

**Comment by darenm** [comment]
Thanks for responding. The primary difference between the scenario you have outlined and the effect I desire is that the background is arbitrary and I was hoping to achieve a transparency effect where the background would show through the control. From what I have seen, that is not possible, so the only viable approach is similar to that which you have suggested - determine the portion of a background image that would appear, alpha mask that, then place it above the element visual. 

Now, is it possible to get at the background to an element by using create backdrop? Time for more digging!

**Comment by sohchatt** [comment]
You are correct in stating that a BackdropBrush painted on a SpriteVisual would get you access to all the visual content "under" that SpriteVisual. You may want to note, however, that when you mask this background content and then draw it on top of itself, there should be no noticeable fade. This is because overlaying masked content over the content itself will effectively undo the effects of masking!

**Comment by darenm** [comment]
Yeah - the point is I want what is "under" the ListView and want to mask that, not the result of the composition of the ListView with the background, but I don't think there is a way for me to be able to do this. I'm quite surprised actually...

**Comment by sohchatt** [comment]
Sorry I was not able to understand the exact problem you were trying to address in the first attempt. There is a way to get the background content without running into the problems of BackdropBrush that I mentioned, but, before I outline the steps needed, I should point out that it isn't straightforward! 

1. You can get a RenderTargetBitmap of the background content you have loaded through XAML.
2. You will want to load either all or the relevant pixels from this RenderTargetBitmap to a CompositionDrawingSurface using Win2D.
3. You can calculate the particular subrect of pixels from the RenderTargetBitmap that you wish to load to the CompositionDrawingSurface by doing the necessary calculations resulting from your XAML Layout. Expressions may come in handy should your dynamic resizing be a concern. Conversely, you could load the entire RenderTargetBitmap (instead of only loading in pixels from the subrect you care about) to a CompositionDrawingSurface and use the Offset property on the CompositionSurfaceBrush to position your surface appropriately relative to the SpriteVisual (maskSprite in my earlier reply above). Again, you may want to use Expressions to calculate the transformations based on your XAML Layout (and use the correct Stretch and Alignments on your SurfaceBrush).
4. Input this CompositionDrawingSurface to a CompositionSurfaceBrush. Alpha-mask this with a gradient mask and paint the resulting MaskBrush onto a SpriteVisual as shown in the reply above.

Just a note that RenderTargetBitmap only captures content loaded through XAML elements (it does not capture the contents of Windows.UI.Composition objects).

Here's a rough example of what loading the pixels from a RenderTargetBitmap onto a CompositionDrawingSurface might look like:

```
       private async Task GetGridSnapshot()
        {
            // capture RenderTargetBitmap of the uielement 
            var bitmap = new RenderTargetBitmap();
            await bitmap.RenderAsync(MyBackgroundGrid);
            var pixels = await bitmap.GetPixelsAsync();
            
            // load the pixels from RenderTargetBitmap onto a CompositionDrawingSurface
            CompositionDrawingSurface uiElementBitmapSurface;
            using (var canvasBitmap = CanvasBitmap.CreateFromBytes(_device, pixels.ToArray(), bitmap.PixelWidth, bitmap.PixelHeight, DirectXPixelFormat.B8G8R8A8UIntNormalized))
            {
                uiElementBitmapSurface = _compositionGraphicsDevice.CreateDrawingSurface(new Windows.Foundation.Size(canvasBitmap.SizeInPixels.Width, canvasBitmap.SizeInPixels.Height), DirectXPixelFormat.B8G8R8A8UIntNormalized, DirectXAlphaMode.Premultiplied);
                using (var session = CanvasComposition.CreateDrawingSession(uiElementBitmapSurface))
                {
                    session.DrawImage(canvasBitmap);
                }
            }

          // assign CompositionDrawingSurface to the CompositionSurfacebrush with which I want to paint the relevant SpriteVisual
           _backgroundImageBrush.Surface = uiElementBitmapSurface;
       }

```

**Comment by msftdavid** [comment]
Closing as it seems like there is an answer to this issue. Please re-open if you still have problems achieving the desired effect.

**Comment by darenm** [comment]
Thanks for the comments - I will give this a shot/

**Comment by darenm** [comment]
@sohchatt Thank you so much for your assistance. I have the solution working and I thought I would share it here.

Here is the UI:
![image](https://cloud.githubusercontent.com/assets/1674843/19006933/85153e34-871f-11e6-9e5c-3f6d359ca931.png)

This is the XAML for the view:

```XAML
    <Grid x:Name="LayoutRoot">

        <Image x:Name="BackgroundImage"
               ImageOpened="ImageBrush_OnImageOpened"
               Source="../Assets/blue-star-background-wallpaper-3.jpg"
               Stretch="UniformToFill" />

        <GridView x:Name="Posters" Margin="200,48">
            <GridView.Resources>
                <Style TargetType="ListViewItem" />
                <Style TargetType="Image">
                    <Setter Property="Stretch" Value="UniformToFill" />
                    <Setter Property="Width" Value="300" />
                    <Setter Property="Margin" Value="12" />
                </Style>
            </GridView.Resources>
            <GridViewItem>
                <Image Source="Assets/Posters/1.jpg" />
            </GridViewItem>
            <GridViewItem>
                <Image Source="Assets/Posters/2.jpg" />
            </GridViewItem>
            <GridViewItem>
                <Image Source="Assets/Posters/3.jpg" />
            </GridViewItem>
            <GridViewItem>
                <Image Source="Assets/Posters/4.jpg" />
            </GridViewItem>
            <GridViewItem>
                <Image Source="Assets/Posters/5.jpg" />
            </GridViewItem>
            <GridViewItem>
                <Image Source="Assets/Posters/6.jpg" />
            </GridViewItem>
            <GridViewItem>
                <Image Source="Assets/Posters/7.jpg" />
            </GridViewItem>
            <GridViewItem>
                <Image Source="Assets/Posters/8.jpg" />
            </GridViewItem>
            <GridViewItem>
                <Image Source="Assets/Posters/9.jpg" />
            </GridViewItem>
            <GridViewItem>
                <Image Source="Assets/Posters/10.jpg" />
            </GridViewItem>
            <GridViewItem>
                <Image Source="Assets/Posters/11.jpg" />
            </GridViewItem>
            <GridViewItem>
                <Image Source="Assets/Posters/12.jpg" />
            </GridViewItem>
        </GridView>
    </Grid>
```

And here is the code:
```csharp
        private bool _imageLoaded;

        // this is an initial way of handling resize 
        // I will investigate expressions
        private async void OnSizeChanged(object sender, SizeChangedEventArgs args)
        {
            if (!_imageLoaded)
            {
                return;
            }
            await RenderOverlayAsync();
        }

        private async void ImageBrush_OnImageOpened(object sender, RoutedEventArgs e)
        {
            _imageLoaded = true;
            await RenderOverlayAsync();
        }

        // this method must be called after the background image is opened, otherwise
        // the render target bitmap is empty
        private async Task RenderOverlayAsync()
        {
            // setup composition
            // (in line here for readability - will be member variables moving forwards)
            var compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;
            var canvasDevice = new CanvasDevice();
            var compositionDevice = CanvasComposition.CreateCompositionGraphicsDevice(compositor, canvasDevice);

            // determine what region of the background we need to "cut out" for the overlay
            GeneralTransform gt = Posters.TransformToVisual(LayoutRoot);
            Point elementPosition = gt.TransformPoint(new Point(0, 0));

            // our overlay height is as wide as our poster control and is 30 px high
            var overlayHeight = 30;
            var areaToRender = new Rect(elementPosition.X, elementPosition.Y, Posters.ActualWidth, overlayHeight);

            // Capture the image from our background.
            //
            // Note: this is just the <Image/> element, not the Grid. If we took the <Grid/>, 
            // we would also have all of the child elements, such as the <GridView/> rendered as well -
            // which defeats the purpose!
            // 
            // Note 2: this method must be called after the background image is opened, otherwise
            // the render target bitmap is empty
            var bitmap = new RenderTargetBitmap();
            await bitmap.RenderAsync(BackgroundImage);
            var pixels = await bitmap.GetPixelsAsync();

            // we need the display DPI so we know how to handle the bitmap correctly when we render it
            var dpi = DisplayInformation.GetForCurrentView().LogicalDpi;

            // load the pixels from RenderTargetBitmap onto a CompositionDrawingSurface
            CompositionDrawingSurface uiElementBitmapSurface;
            using (
                // this is the entire background image
                // Note we are using the display DPI here.
                var canvasBitmap = CanvasBitmap.CreateFromBytes(
                    canvasDevice, pixels.ToArray(),
                    bitmap.PixelWidth,
                    bitmap.PixelHeight,
                    DirectXPixelFormat.B8G8R8A8UIntNormalized,
                    dpi)
            )
            {
                // we create a surface we can draw on in memory.
                // note we are using the desired size of our overlay
                uiElementBitmapSurface =
                    compositionDevice.CreateDrawingSurface(
                        new Size(areaToRender.Width, areaToRender.Height),
                        DirectXPixelFormat.B8G8R8A8UIntNormalized, DirectXAlphaMode.Premultiplied);
                using (var session = CanvasComposition.CreateDrawingSession(uiElementBitmapSurface))
                {
                    // here we draw just the part of the background image we wish to use to overlay
                    session.DrawImage(canvasBitmap, 0, 0, areaToRender);
                }
            }

            // assign CompositionDrawingSurface to the CompositionSurfacebrush with which I want to paint the relevant SpriteVisual
            var backgroundImageBrush = _compositor.CreateSurfaceBrush(uiElementBitmapSurface);

            // load in our opacity mask image.
            // this is created in a graphic tool such as paint.net
            var opacityMaskSurface = await SurfaceLoader.LoadFromUri(new Uri("ms-appx:///Assets/OpacityMask.Png"));

            // create surfacebrush with ICompositionSurface that contains the background image to be masked
            backgroundImageBrush.Stretch = CompositionStretch.UniformToFill;

            // create surfacebrush with ICompositionSurface that contains the gradient opacity mask asset
            CompositionSurfaceBrush opacityBrush = _compositor.CreateSurfaceBrush(opacityMaskSurface);
            opacityBrush.Stretch = CompositionStretch.UniformToFill;

            // create maskbrush
            CompositionMaskBrush maskbrush = _compositor.CreateMaskBrush();
            maskbrush.Mask = opacityBrush; // surfacebrush with gradient opacity mask asset
            maskbrush.Source = backgroundImageBrush; // surfacebrush with background image that is to be masked

            // create spritevisual of the approproate size, offset, etc.
            SpriteVisual maskSprite = _compositor.CreateSpriteVisual();
            maskSprite.Size = new Vector2((float)Posters.ActualWidth, overlayHeight);
            maskSprite.Brush = maskbrush; // paint it with the maskbrush

            // set the sprite visual as a child of the XAML element it needs to be drawn on top of
            ElementCompositionPreview.SetElementChildVisual(Posters, maskSprite);
        }
```
