### ISSUE TITLE
Interaction 3D - Always crashed when trying to pinch and zoom

### ISSUE THREAD

**Issue by gratitudepod** [Microsoft/WindowsUIDevLabs#138]
I am running the Interaction 3D with Windows 10 anniversary. It was always crashed whenever I tried to pinch and zoom. It also crashed if I used the mouse instead of the pinch/zoom in the simulator. The pinch and zoom were never worked as expected. 

I did try to disable the Live Visual Tree debugging but it did not help. 

Below is the error message, and I am attaching the exception screenshot for a complete detail.

"An exception of type 'System.UnauthorizedAccessException' occurred in CompositionSampleGallery.exe but was not handled in user code

Additional information: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))"

Please help.
Thanks!

![capture1](https://cloud.githubusercontent.com/assets/7458533/17459982/4018a8dc-5c1f-11e6-93e5-1db33a4a76fd.PNG)

**Comment by likuba** [comment]
Thanks @gratitudepod for letting us know.  We'll take a look at this and get back to you.  To make it easier for us to repro--which build/SDK are you using?

**Comment by gratitudepod** [comment]
Hi Lindsay,

I'm running Visual Studio Enterprise  v14.0.25425.01 Update 3. My development is Dell Precision 4600 Windows 10 N x64 Anniversary 1607. For the SDK, I am not sure how to look it up for the exact version number but I use the latest SDK that got installed with visual studio 2015 Update 3. By the way, when I built the WindowsUIDevLabs, I only targeted Build 14393 as minimum and maximum (see attached images).

Thanks for your help!

![capture2](https://cloud.githubusercontent.com/assets/7458533/17489768/aee2703c-5d6d-11e6-9aec-c6c4399d5c86.PNG)


![capture3](https://cloud.githubusercontent.com/assets/7458533/17489796/c002c902-5d6d-11e6-954b-9355a13be64b.PNG)

**Comment by gratitudepod** [comment]
Hi Likuba,

I wonder if you get a chance to look into this issue.

Thanks.

**Comment by decademoon** [comment]
I get this error too. I hope it won't be an issue that makes the InteractionTracker completely unusable.

[Mike Taulty's blog](https://mtaulty.com/2016/07/06/windows-10-uwp-and-composition-experimenting-with-interactions-in-the-visual-layer/) has a code snippet where he wraps TryRedirectForManipulation in a try-catch block with the following comment:

```
// TBD: I can get an UnauthorizedAccessException here if I pass 
// a point that's beyond the bounds of my rectangle and I haven't
// figured out why yet.
```

but there's no more information about it anywhere that I know of.

**Comment by likuba** [comment]
Sorry for not getting back to you sooner.

We had a few bugs like this when the feature was under development, so it is definitely possible that this is a product bug that we didn't find.  

The mouse input is a bug in the sample--we should only be attempting to redirect pointers of type touch, so I'll push a small update to get that piece fixed.

Unfortunately, just zooming on the interactions3d app does not repro the issue for me.  @gratitudepod  Are you just doing a regular touch zoom on a touch monitor, or on the touchpad?  Or is it on a vm/emulator?  In the past when we found some similar issues they tended to be hardware specific, so knowing the exact repro steps is super helpful here.

@decademoon is your repro the same? or in your own app?

**Comment by decademoon** [comment]
@likuba I've since updated my UI quite a bit and the issue doesn't seem to happen as frequently (I have a complex layout with 2 interaction trackers for swiping up/down and left/right on nested transformed elements, with a ListView underneath). I will try to isolate the cause and upload a small project to github.

**Comment by likuba** [comment]
The ScrollViewer shouldn't be interfering--in theory the InteractionTracker would be intercepting the input before the ScrollViewer even sees it, but it is still possible there's a bug there.  Definitely looking forward to a reduced repro if you are able to pinpoint it (and your UI when you are ready to release it!).

**Comment by decademoon** [comment]
@likuba I managed to create a small repro of the bug [here](https://github.com/decademoon/InteractionTrackerBug) (which is nothing special, really). The bug is easiest to reproduce using the simulator. It can happen using the mobile emulator and a real device too, but it doesn't occur as frequently. I also have a crash dump [here](https://1drv.ms/u/s!ApBG9v0iJw9nqrYnRTOXigQwsjxjZg) which might be helpful.

I've recorded a [video](https://www.youtube.com/watch?v=MPZHjFa_emY) showing what happens. Incidentally, you can see in this video some odd sporadic behaviour which I can't explain (maybe another  bug?).

**Comment by likuba** [comment]
@decademoon thanks for the reduced repro.  We're filing a product bug to investigate this further and see if we can figure out why this is hitting.

**Comment by JustinXinLiu** [comment]
I am getting this error *only* when I put a breakpoint in code and then start debugging.

**Comment by likuba** [comment]
@decademoon sorry for the delay in getting back to you on this one.  We think there are a few things going on here.

First of all, there is a bug where InteractionTracker is having trouble capturing input from TryRedirectforManipulation if the contact has left the screen when the call is processed.  We're looking into fixing this, but for now it will happen when there are quick flicks or the processing of the call is delayed for some reason (perhaps like the breakpoint case above, @JustinXinLiu ?).  When this happens, you should be getting an E_ACCESSDENIED error.  To prevent the app from crashing you should make sure to handle this error.  For this specific case, once our above bug is fixed it should capture the input rather than sending E_ACCESSDENIED, but this error could also fire if you try to capture a contact that you can't capture (for example, if it is owned by another process, not a supported input type, etc) so it is good practice to handle it anyway.  

This has also made me realize that our samples aren't following our own best practice for this one, so I'll also file some tasks to fix those up and update our MSDN documentation for posterity :)

**Comment by likuba** [comment]
@decademoon 
With recent changes to the Interactions3D sample you shouldn't be hitting this issue anymore.  
Thanks!
