### ISSUE TITLE
Tying composition to how much of a listview container is visible on sceen?

### ISSUE THREAD

**Issue by mhomde** [Microsoft/WindowsUIDevLabs#139]
Hi,

I have this effect where I want to fade and deblur items in a listview  as they become totally visible on screen. Ie for simplicity's sake we can say if the container intersects the screen with 50% it should be 50% blurred, if it's 10% visible it should be 90% blurred etc.  

Currently I'm achieving this by  hooking up to the listview's scrollviewer's Viewchanged event, and then iterating through the visible indices calling ListView.ContainerFromIndex(i) on those and calculating the item rect and how it intersects with the listsviews. Then I can get a percentage visible from that.

It works pretty good but looking at the kinda of binding used in say Parallax using the composition API and its great performance I was hoping that just maybe there was as composition way to achieve this as well?  Thanks in advance! 

best regards
/Mattias

**Comment by patsiu** [comment]
Hey @mhomde !

Thanks for reaching out with your question. The short answer to your question is unfortunately you are not able to apply a Composition effect to a "leaf" node (individual list view item) in the XAML/Composition interop story. This is something the team is figuring out for a future release.

In general, you can use ExpressionAnimations to bind the blur amount of a blur effect to be dependent on something like Offset. But like I mentioned earlier, we cannot apply a Composition Effect to an Interop Visual we get from a UIElement, and thus not able to animate it. I'm also gonna add @JasterAtMicrosoft and see if he has any workarounds.

**Comment by mhomde** [comment]
Thanks for the reply!

Yeah I figured it might be a tricky one since it depends on the list item container. I appreciate any workarounds or if not possible it would make for a good addition for future versions I think. 

Wanting to manipulate effects on an list item depending on it's position and screen intersections seems like a useful scenario

**Comment by JasterAtMicrosoft** [comment]
Hi @mhomde ,

It should be possible to achieve this. Though you can't blur an individual item, you can use a **BackdropBrush** to add an overlay that blurs the contents of a list item. See #137 for some pointers on how to make this performant.

To drive the animation of the blur, you will want to use an expression based on the position of the list, which is demonstrated in the ParallaxingListItems sample. Since you probably want to re-use a blur effect for all list items, you may want to animate the Opacity of the SpriteVisual holding the blur effect instead of the effect itself.
