### ISSUE TITLE
Queueing up actions on Composition Thread

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#146]
I have a CustomPanel which is used to display images.

I have overridden the following method

```C#
protected override Size ArrangeOverride(Size finalSize)
```

Inside this method I have the logic for loading the image onto **CompositionDrawingSurface**.

Now the problem with **ArrangeOverride** method is that you cannot have an _await_ call within it. Also the computation for loading and resizing the image onto the **CompositionDrawingSurface** is a bit time consuming due to which the refresh of the panel stutters a bit.

I tried using a **Timer** to fire a _Tick_ event. In the method which is called response to this event I am updating the images. But this creates a longer lag during refresh.

```C#
Timer updateTimer;

private CustomPanel()
{
    updateTimer = new Timer(UpdateSize, TimeSpan.FromMilliseconds(-1), 
                   TimeSpan.FromMilliseconds(-1));
}

protected override Size ArrangeOverride(Size finalSize)
{
    updateTimer.Change(TimeSpan.FromMilliseconds(0), .FromMilliseconds(-1));
}

private void UpdateSize(object info)
{
    // Update CompositionDrawingSurface here
}
```

So my question is
Just like Dispatcher.RunAsync() allows you to queue up method calls on the UI thread, is there a way to queue up method calls on the Composition Thread?

Or is there a better approach to run the **UpdateSize()** method on a separate thread?

**Comment by scott-moore-ms** [comment]
Hi Ratish, a few thoughts here - 

- You can't use 'await' in ArrangeOverride because it's not an async method.  What 'async' means to a caller is that the code being invoked can go kick off an asynchronous task, and return an object back to the caller (a Task) which can notify it when the operation has completed so they can proceed with their own logic.  C# adds a lot of magic sauce to make this pattern look more natural, so that you don't typically see the task part of it, you just use 'await'.  But, the implications of making ArrangeOverride async would be that layout itself would potentially need to pause itself while your arbitrary task went off and computed its results.  In this case, there's no benefit to supporting that - layout can't proceed until it has an answer (it needs to know how big your item is).

- Every CompositionObject has a Dispatcher property on it, which you can use to enqueue work to its thread via RunAsync, so that is how you can schedule work to run on the Composition thread.

- _However_ if what you're doing in UpdateSize takes a long time to execute (which it sounds like), you probably don't want to execute it on the Composition/UI thread at all.  A thread can only do one thing at a time, so if it's busy cranking through your UpdateSize method, it's not doing other UI-related work, and you've already indicated that it's too expensive to perform during ArrangeOverride.  It sounds like what you would want to do is perform your heavy work off the UI thread (ex use ThreadPool.RunAsync to schedule it) and then when that's completed, use the CoreDispatcher to post a notification back to the UI thread to rerun layout based on the new results.

**Comment by ratishphilip** [comment]
@scott-moore-ms Thanks for the detailed explanation.
It clarifies a lot of doubts and introduces a few :)
- Does the Dispatcher property of CompositionObject refer to the Dispatcher which manages the UI thread or is it a separate entity which manages the Composition Thread?
- I am under the impression that the in the **MeasureOverride** method the parent asks the child how much size it needs to layout itself and in the **ArrangeOverride** method the parent provides a _finalSize_ to the child to perform its layout. So if both the methods primary deal with passing information about layout sizes, in which method (or override, if any) does the actual render happen. If such a method exists which supports queueing of asynchronous methods, it would be great.

 The problem I faced was that UpdateSize method could be called only after the _finalSize_ is obtained in the **ArrangeOverride** method. _finalSize_ value is required to perform the necessary calculation in my UpdateSize method.

To explain it further, my custom panel hosts several visuals each of which displays an image. While looping through the visuals, the UpdateSize method is called for each of them. Earlier the UpdateSize method was an async method. So putting an await within the loop caused the thread to asynchronously wait until each of the visual UpdateSize is completed and then proceeded to the next visual. _**What I wanted to achieve is that UpdatedSize method should execute in separate threads for each visuals' image.**_
I converted the UpdatedSize to a synchronous method (thus removing the need to _await_) by removing the redundant asynchronous entities and Task.Run() encapsulations.
But still there was a noticeable lag (but no flickering) while updating the images in the visuals.

I am not sure if calling Dispatcher.RunAsync() or ThreadPool.RunAsync() within ArrangeOverride is appropriate because both of them are asynchronous methods. So the question how to trigger a method, which would spawn the necessary threads to update the images, after ArrangeOverride?

What I intend to create is a pattern which can be used by developers to initialize and update Composition elements (just like Layout pass, I would like to create a Composition pass which would provide an init and update overridable methods). A similar example of this would be the **CanvasAnimatedControl's
**CreateResources** and **Draw** events.**

**P.S.** _On the brighter side, after reading your reply, I refactored my code in such a way that made the UpdateSize method redundant and need not be called. Thus the UI is faster and works as per my expectation._

**Comment by scott-moore-ms** [comment]
> Does the Dispatcher property of CompositionObject refer to the Dispatcher which manages the UI thread or is it a separate entity which manages the Composition Thread?

Every CompositionObject has an associated Compositor.  The Dispatcher property refers to the Dispatcher for the thread which the owning Compositor was created on, which is the same as your UI thread in this case.  (One alternate case might be if you had a multi-window app.  Each window operates on its own thread, and could have its own Compositor, so _which_ thread becomes more relevant here).

> I am under the impression that the in the MeasureOverride method the parent asks the child how much size it needs to layout itself and in the ArrangeOverride method the parent provides a finalSize to the child to perform its layout. So if both the methods primary deal with passing information about layout sizes, in which method (or override, if any) does the actual render happen. If such a method exists which supports queueing of asynchronous methods, it would be great

I don't know specifically where the actual Render happens or what overload you would override to perform it, but if there were such a method, it almost certainly does not allow for the async/await pattern within it, for the same reason the layout methods don't support it.  A large point of asynchronous methods is to improve responsiveness to the user (provide an easy mechanism to avoid doing long-running operations on the UI thread, allowing other things to occur in the meantime).  Part of user responsiveness is seeing actual output produced on the screen, and so having the render walk complete is an integral part of that =)

> I am not sure if calling Dispatcher.RunAsync() or ThreadPool.RunAsync() within ArrangeOverride is appropriate because both of them are asynchronous methods. So the question how to trigger a method, which would spawn the necessary threads to update the images, after ArrangeOverride?

ThreadPool.RunAsync() would be what you should use, but you can't use await to block the UI thread waiting for the results.  My general suggestion for this class of problem is to enqueuer the concurrent work when your UI Element is materialized so that it can run in the background, and post updates back to the UI thread when the work is complete so that your UI is updated.  Having each image being its own individual task is a very simple model and often works well.   Depending on what exactly you're after, you can build fancier mechanisms (ex if you want to load 10 images and only update the UI when all 10 of them have completed).

**Comment by ratishphilip** [comment]
@scott-moore-ms  Thank you!
