### ISSUE TITLE
Expression animation stops working in 14393

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#149]
This can be replicated in [one](https://github.com/clarkezone/UWPCompositionDemos) of James' GitHub repo.

As soon as I change the *Target version* to _14393_, the background image loses all movement.

How to fix this? Cheers.

**Comment by robmikh** [comment]
This is due to the changes to [XAML-Composition interop](https://github.com/Microsoft/WindowsUIDevLabs/wiki/XAML-Composition-Interop-Behavior-Changes).

It's not as straight-forward as some other examples of this, as the background `Image` doesn't seem to be setting any properties that would effect XAML layout. However, because it is in a `Grid`, the default position is actually in the center, which triggers XAML to change the `Offset` property of the visual.

A workaround is to wrap the `Image` in a `Border` that sits in the middle of the `Grid` like so:

```
<Grid Background="Black">
    <Border HorizontalAlignment="Center" VerticalAlignment="Center">
        <Image Name="background" Source="Assets/untitled.png"/>
    </Border>
    
    <ScrollViewer Name="myScroller" Margin="5,5,5,5">
```

**Comment by JustinXinLiu** [comment]
Thanks Rob! Just wonder why setting `HorizontalAlignment="Center" VerticalAlignment="Center"` on the `Image`, without the use of the `Border` won't work?

**Comment by robmikh** [comment]
The issue is that when an element is positioned anywhere other than (0, 0) relative to its parent, then XAML will set that visual's `Offset` property. This is why not only setting

**Comment by JustinXinLiu** [comment]
Oh gotcha! That means just setting `HorizontalAlignment="Left" VerticalAlignment="Top"` on the `Image`, should work too. Of course if I want the `Image` to sit in the middle I will have to manually reposition it whenever the `Size` of the parent `Grid` is changed.

Thanks heaps Rob!
