### ISSUE TITLE
Questions about disposal

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/WindowsUIDevLabs#152]
Hey folks,

I have a question about `Dipose()` on all of the CompositionObjects. So, all of them have it. The question is do we actually have to call it to clean up when we create our objects using the   ##compositior's `CreateXXX` methods to avoid small memory leaks?

I ask because very few if any of the samples actually dispose anything. Is it safe to leave them all undisposed? The C# memory profiler doesn't seem to pick up composition objects whenever I test, and unless I keep a direct reference to them, WeakReferences also immediately lose their references to composition objects until I indirectly reference them again, so it's difficult for me to work out whether or not I'm actually leaking unmanaged memory here. (Presumably because they're kernel objects underneath... but surely the C# representation of them should be alive?)

At the moment I'm going through the hoops of keeping track of every batch, animation, insetclip and easing that I create so I can manually dispose when I'm done, though would be good to know whether it's worth the effort!

**Comment by JohnnyWestlake** [comment]
Just pinging this to see if there's any guidance from anyone on the composition team at Microsoft?

**Comment by jeffstall** [comment]
Hi Johnny,

Thanks for bringing up the question about how to properly Dispose() CompositionObjects. As you have noticed, we added Dispose() in our API because we want to encourage applications to aggressively Dispose() objects to free up system resources instead of relying solely upon .NET GC occurring at unpredictable intervals.

We are aware that we need to write up clear and comprehensive guidance about effective memory management and object lifetime. It’s not something that can be easily answered in an email or forum discussion. We also need to upgrade SampleGallery and other samples to provide clear templates about these best practices.

If there is a specific thing that you’re wondering about, that would help to provide more context for an answer.

Thanks!
~ Jeffrey

**Comment by decademoon** [comment]
I don't believe it is _required_ to call Dispose(), the GC will get around to it eventually once there are no references to that object. But it does give developers the opportunity to proactively dispose of unmanaged resources. It probably depends on the kind of resource as to whether calling Dispose() would be advisable (it's not like a clip resource would consume more memory than a visual, not to mention a visual probably has a hardware texture too). Hopefully we get more info about this once the docs get updated.

**Comment by stonstad** [comment]
This is a good discussion.  OK, so the guidance provided above seems counter intuitive to me.  Aren't these C# objects creating unmanaged resources which result in memory pressure not visible to the garbage collector?  i.e. texture allocation can be very expensive at large resolutions and the GC won't know to free the resource because the pinned resources is unmanaged.

...if this is true, I would think that Dispose should **always** be called for these instances.  Please set me straight!

**Comment by daneuber** [comment]
Circling back around to this discussion. Proper use of Dispose and more generally recommended memory management practices may vary based on environment and code configuration; it's difficult to provide broadly scoped recommendations without running into specific instances where it doesnt apply. We are happy to answer more detailed questions with code examples in regard to specific experiences you're trying achieve, so please open a new Issue if you have specific questions. In the mean time I'm going to go ahead and close this Issue, and we'll take the feedback that we should consider providing more detailed lifetime management information on our docs (feel free to comment or vote on this if you feel that would be helpful)

**Comment by stonstad** [comment]
@daneuber While nothing you stated is untrue, it is worth noting that we are trying to determine if these classes leak memory if not disposed.  If they maintain references to unmanaged resources it becomes an important design consideration and these examples do not appear to clean up memory.  Your answer regarding a generalalized approach does not address this core question.

**Comment by robald** [comment]
@stonstad Your understanding is correct regarding the importance of Dispose with respect to unmanaged resources.  Many things in the Composition APIs are backed by unmanaged resources such as shaders, textures, etc and calling Dispose() explicitly is recommended to ensure those resources are released as soon as they are no longer needed.  Failing to dispose objects explicitly should not lead to leaks as the GC should eventually collect them once they are no longer referenced, but Dispose is recommended especially for things like surfaces.
