### ISSUE TITLE
How to scale up a Path (vector) xaml element without losing the sharpness?

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#175]
In our new app we need to manipulate thousands of `Path` XAML objects on a canvas and to get the best performance we recently started playing with the Composition API.

Everything else seems to be working seamlessly except when I try to manipulate the "pinch and zoom" gesture on a `Path` by animating its `Scale`, it becomes really blurred and even stays blurred after the animation finishes. I guess the animation engine must have used a bitmap in the process.

I have also tried to animate its `Size` but it doesn't seem to do anything (this is probably my second question, how to update the `Size` of a XAML element's `Visual`?).

Besides, if I have a `Path` element sit inside a `ScrollViewer` which enables zooming, when I zoom it in it gets a little bit blurry but as soon as my fingers lift up the blurriness goes away; when I zoom it out, it stays sharp all the time. Ideally we would want it to maintain crystal sharp but this is still acceptable for now. But the problem is that we cannot use the default `ScrollViewer` control due to some of its limitations.

I did manage to achieve a similar result by using `Scale` first, then once the animation finishes, set its `Scale` back to `Vector3.One` and manually update the `Path` element's `Width` and `Height` to match their scaled values.

Just wonder if there's a better way to achieve what we want? Thanks guys!

**Comment by JohnnyWestlake** [comment]
Scaling via composition won't re-render the original texture / element at any point as the XAML engine itself needs to do the re-render, and the XAML engine has little to no awareness of what Composition layer is doing so won't do anything in response to pretty much anything composition is doing -  which is _very_, _very_ nice for performance, not so useful for you.


Scaling via a standard XAML RenderTransform / Composite transform will re-render after the animation has completed, though due to threading / performance considerations it will never stay clear the whole way through a scale. (Pre-Windows 10, this WinRT XAML model actually had much more favourable threading that would re-render faster / more often, but whatever changes were made to allow composition had a knock on effect in quite a few animation areas in XAML). 

But you can't link RenderTransforms to Composition interactions easily, and XAML manipulation events are hardly smooth. So what you've got isn't a bad solution at all.


You can also try looking at Win2D - it's a lot more manual but if your machines have the power it will let you re-draw during scaling every single frame but you'll probably find that may end up being quite processor intensive and may start becoming jerky.

(FYI there may be some minor inaccuracies in all the above but I think it's generally on the right path)

**Comment by JustinXinLiu** [comment]
You are right - using Win2D to re-draw does make it jerky after adding thousands of elements on the canvas. This is what we currently have and want to improve on. :)

I too have noticed the blurriness in Windows 10 when using scale (or even translate) render transform animations, a step backwards I'd say.

**Comment by JasterAtMicrosoft** [comment]
Hi Justin,

As you noticed there is a limitation with interop for animations where the framework won't re-draw the content that's been animated by a Windows.UI.Composition animation. The workaround you are doing to resize the content at the end of the animation is probably the best option and as Johnny mentioned this is the same as what you would get using a Storyboard animation.

You might get better performance with Win2D using a [CanvasVirtualControl ](https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_UI_Xaml_CanvasVirtualControl.htm)in a ScrollViewer, drawing all of the objects to the same surface instead of in different elements. Of course you would lose out on stuff like simple hit testing and interaction with the individual Paths.

Also tagging this as "feedback" for the issue of re-rasterizing during an animation. Johnny I believe you're right this did change as a result of some architectural changes in RS1.

**Comment by JustinXinLiu** [comment]
Thanks @JasterAtMicrosoft.

An iOS dev sitting next to me just showed me how he didn't have to do anything and the paths always stay crystal sharp during scaling animation on an iPad Pro.

Would "re-rasterizing during an animation" achieve the same result?

**Comment by JasterAtMicrosoft** [comment]
I can't speak to what iOS is doing, but there are known improvements we can make here. It's good to know that this is something you folks care about.

**Comment by JustinXinLiu** [comment]
Yeah that's probably one of the few things their iOS app has that looks better than our UWP app. :P Would love to tick this off the list too!

**Comment by ratishphilip** [comment]
@JustinXinLiu 
If you can convert your Path XAML objects to equivalent **CanvasGeometry** objects, then you can use the **Transform** property to scale the geometries.
However, one thing you should note is that, when you scale a small CanvasGeometry to a large amount, the **flattening** of the curves becomes a little bit evident. (More details about flattening [here](https://msdn.microsoft.com/en-us/library/windows/desktop/dn363632%28v=vs.85%29.aspx)) (Zooming out does not have this issue )

To avoid that I would suggest the following workaround.
Say your app allows the scaling factor from 1 to 10 for pinch/zoom.

You can define your CanvasGeometry for a scale factor of 10 as the default. This way for the scale factor of 1, you will be scaling down the geometry and the flattening will not be visible.

Now this adds another overhead. You must manually write your animation code. To achieve that, this is what I have done.

1. Use a CanvasAnimatedControl to host your CanvasGeometries.
2. Use [Robert Penner's Easing Equations ](http://robertpenner.com/easing/) to define your animation formula.
3. In the Update event of the CanvasAnimatedControl, update the scale of the CanvasGeometries based on the scale calculated from the animation formula.
4. In the Draw event of the CanvasAnimatedControl, render the scaled CanvasGeometries.

**Comment by Pierce913** [comment]
Hi @ratishphilip 
I work with Justin and what you describe is very similar to what we have already implemented. We tried drawing the entire content using both CanvasControls and CanvasAnimatedControls... and rendered the geometries using CanvasGeometry. This works well and is quite graceful from an implementation point of view but the Win2D controls seem to fall down in performance when it comes to smoothness. We've found the garbage collector causes pauses on all threads which causes stutter in the animations. There is simply no comparison when we implement the same animations in Composition. It is just always buttery smooth. It is clearly executed on a process with much higher priority than we have access to in a UWP app.

**Comment by ratishphilip** [comment]
Hi @Pierce913 
I think it all depends on the scenario where one is using Composition and Win2d. 
In my case, I needed to stop and start animations at a very fast pace, requiring me to obtain the intermediate values during the animations. Now it is not possible to obtain intermediate values of animated properties in Composition. So I tried a mix of Win2d and Composition. Win2d's CanvasAnimatedControl provided the Update and Draw methods which allowed me to provide a custom animation and have the intermediate values for any frame.
But starting and stopping animation at such a fast rate using Composition did not give me a good performance (I was getting 35 - 48 FPS).
So I had to fully resort to Win2d only (and used the steps I mentioned in my earlier comment) and now I am getting buttery smooth animation (57-60 FPS).

I had a look at your scenario mentioned [here](https://github.com/Microsoft/Win2D/issues/454).

Well, Win2d and Composition provide multiple ways to arrive at the solution to a problem and there might be performance difference in each solution.

As I said earlier, it all depends on the scenario and how we approach it (with either Composition or Win2d or a mix of both).

**Comment by Pierce913** [comment]
Yeah to be fair our scenario is not easy. It would be awesome if we could have a high priority dedicated process to execute our win2D code on... then all my problems would be solved :D

**Comment by ratishphilip** [comment]
Well creating multiple CanvasRenderTargets might indeed be costly.
Have you considered using CanvasSwapChain? I am not sure if it would suit your scenario. Just a hunch.

**Comment by Pierce913** [comment]
Isn't the AnimatedCanvasControl already based on a swap chain?

**Comment by ratishphilip** [comment]
Yes, it uses that internally.

**Comment by Pierce913** [comment]
Also I have observed that starting and stopping composition animations is sluggish compared to win2D

**Comment by ratishphilip** [comment]
Yeah true. Implementing my own animation gave me better performance.

You must focus on either finding an alternative to CanvasRenderTarget (which can be resized) or pooling the CanvasRenderTargets as suggest by Shawn.
If you are using CanvasAnimated control, streamlining your code in the Update and Draw handlers should improve your app's performance.

**Comment by Pierce913** [comment]
For anyone interested I came across this thread which sounds similar to some of the issues I was seeing with Win2D performance.

https://github.com/Microsoft/Win2D/issues/185

**Comment by daneuber** [comment]
We're tracking general shape support under the request [here](https://developer.microsoft.com/en-us/windows/platform/features/animatedvectorgraphicssupportinthevisuallayer/?q=vector%20graphics). Closing this issue, please feel free to upvote on the public backlog.
