### ISSUE TITLE
how to get control as groove music?

### ISSUE THREAD

**Issue by iamstudentVN** [Microsoft/WindowsUIDevLabs#184]
how to get control as groove music? push up a grid to show a listbox below
![kk5qpbf](https://cloud.githubusercontent.com/assets/12800744/20855891/58d1b610-b936-11e6-8348-171f5d9a6705.png)
![v0w3yrz](https://cloud.githubusercontent.com/assets/12800744/20855892/5ac48d44-b936-11e6-8114-c2bbc79a79d9.png)

**Comment by JustinXinLiu** [comment]
Dude you should be asking this sort of questions on StackOverflow.

**Comment by h82258652** [comment]
Groove is coded by Html5(WinJS), not Xaml.
You should ask this question on StackOverflow +1.

**Comment by robmikh** [comment]
@h82258652 That's not true. They use XAML and the Composition APIs.

**Comment by h82258652** [comment]
@robmikh oh yeah, you are right. I have long time don't use Groove. In 10586, I found MS coded it by Html5. It seems they recode it by XAML in 14393.

**Comment by iamstudentVN** [comment]
this is a great control but they do not offer an API or in toolkit :(

**Comment by robmikh** [comment]
@iamstudentVN Start by trying to break the problem down into smaller parts. In the picture there are two important parts, the playback controls and the list. The playback controls look to be on top of the list as far as the XAML order is concerned.

With that in mind, try building two visual states that go from your first screenshot to your second. Then make a button (the arrow at the bottom in this case) switch between visuals states. This will make your app pop from one state to the other. That's a great first start.

Next, apply an Implicit Animation to your playback controls. Now when you switch between visual states the playback controls will animate between the states instead of just popping.  I wrote a blog post about Implicit Animations [here](http://blog.robmikh.com/uwp/xaml/composition/2016/08/18/exploring-implicit-animations.html).

**Comment by iamstudentVN** [comment]
Thank @robmikh. I did step 1. But how to drag up or down it with Animation?

**Comment by msftdavid** [comment]
In addition to @robmikh 's guide to Implicit Animations, it might also be helpful to take a look at the Composition Animation overview: https://msdn.microsoft.com/en-us/windows/uwp/graphics/composition-animation

As others have mentioned though, this sounds like a usage question rather than an issue with a sample or with the Windows UI aspects of the platform. Therefore, we're closing the issue.
