### ISSUE TITLE
InteractionTracker.PositionIntertiaDecayRate is ignored when using intertia modifiers

### ISSUE THREAD

**Issue by decademoon** [Microsoft/WindowsUIDevLabs#186]
I have an interaction tracker configured with two inertia resting values. When swiping, the tracker's position will slowly decay to the nearest resting value, but it does it a bit too slowly. Is it possible to speed up the position decay rate? I've tried setting `InteractionTracker.PositionIntertiaDecayRate` but it has no effect (perhaps this is intentional since the tracker is configured with inertia modifiers).

The only other way I can think of doing this would be to use `InteractionTrackerInertiaMotion` instead of the resting values, but I have no idea how to come up with a second derivative equation to describe the motion that I want. Basically I would need to derive the acceleration equation necessary to bring the position to a specific known value (resting stop) after a specific amount of time has elapsed (the time it takes to come to rest is what I would like to tweak). Do you already have an equation that describes the existing behavior of the tracker's inertia when configured with resting values?

**Comment by patsiu** [comment]
Hey @decademoon!

Thanks for reaching out with your question! Yes, what you are seeing is expected behavior - the PositionInertiaDecayRate value is only applied to InteractionTracker when no InertiaModifiers are present.

But you intuition is correct - You can create an InertiaMotion modifier to change the motion of InteractionTracker  to work in the end points into the equation itself. I don't have an equation that specifically allows you to tweak the time to bring to rest, but you can simulate the motion InteractionTracker takes when InertiaRestingValue modifiers are used with a damped spring. An equation that utilizes position along with Spring components looks like:

F = (P – R) * k + V * D, where P is current position, R is the eventual rest position, k is the spring factor, V is current velocity, and  D is the damping factor.

For this to work like InertiaRestingValue, you would bind the parameters such that P and V are the InteractionTracker’s position and Velocity, and R (a constant) is the intended point of rest. D and k can be tweaked to vary the speed and behavior of the snapping. It is important to point out that the "fastest" way for a spring to come to rest is to make it "critically" damped (which is close to what the motion for InertiaRestingValues is today), so you can tweak the values of D and k to see if something gets you closer to what you're looking for.

Hope this helps ...

**Comment by decademoon** [comment]
I saw the spring equation on the documentation page but dismissed it because I thought that kind of motion would always result in a wobble/spring-like motion. Anyway, I tried it just now with k = 1000 and D = 80 and it actually works pretty well without any springiness (I guess this is what you mean by "critically" damped). Thanks!

But this comes with some other challenges, like `InteractionTrackerInertiaStateEnteredArgs.ModifiedRestingPosition` is now always null. Is this because it is unable to deduce this value from the custom motion I have set?

Another thing: it seems that `InteractionTracker.NaturalRestingPosition` is always 0, even at times when `InteractionTrackerInertiaStateEnteredArgs.NaturalRestingPosition` says otherwise. But referencing this property in an inertia modifier expression (via `this.Target.NaturalRestingPosition`) *does* work. Weird.
