### ISSUE TITLE
Good idea for ElementCompositionPreview.GetElementVisual() to return more capable Visual types?

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#189]
Looks like more relationships are created between XAML and Composition in _14965_. For example, the `Size` of the `Visual` of a `UIElement` is now in sync with the `RenderSize` as well as the `Offset` with the `Margin`.

This is really cool but I just wonder if it'd make much sense to further relate them by overloading the`ElementCompositionPreview.GetElementVisual()` function to take parameters like `Panel` or `Control` and return more capable `Visual` types.

Say if I passed in a `Panel`, I'd expect to have a `ContainerVsiual` returned rather than just a `Visual` so I could add/remove child elements to/from it.

If I passed in a `Control`, I'd expect to have a `SpriteVisual` returned so I could easily animate the color of it, or apply a `Shadow`.

What do you think?

**Comment by sernaj** [comment]
Sorry for the delay in responding. Yes, as you've noticed ElementCompositionPreview is doing a lot more lifting in the Insider builds of the Creator's Update release. To be honest, we're starting to feel like ECP (as we tend to call ElementCompositionPreview ) may be getting a bit overloaded, and looking at the future of ECP for upcoming releases and a lot of our thinking is more in the direction of moving it's functions and exposure into a more mainstream integration to XAML itself rather than extending functions off of it. For example, instead of passing in a UIElement (like button) to ECP you would do interop off the UIElement itself to get Visual layer goodness. Can't be more specific right now (because we haven't really decided on the final details) but we will definitely be sharing ideas out to you folks for feedback as we have more fully formed ideas with Skype feedback sessions. All of that said we won't yank ElementCompositionPreview without a decent deprecation plan as we don't want to break apps using Composition goodness in any way. So you'll likely see things happen in parallel with ECP hanging around until folks are comfortable with the alternative.

**Comment by JustinXinLiu** [comment]
> do interop off the UIElement itself to get Visual layer goodness
I am all for it. This would be a lot more friendly for XAML devs in general.
