### ISSUE TITLE
SVGImagesource flickering

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#199]
Today I started a new test to see if I can animate SVG raw and then change the source using 

     svgsource = new SvgImageSource();
     Image.Source = svgsource;
     svgsource.SetSourceAsync(memoryStream);

https://github.com/juanpaexpedite/SVGAnimations

Of course I have to learn how to optimize to edit just parts of the svg string, and recreating the source stream.

But at the moment the issue I have is when I call SetSourceAsync again it flickers too much. The svg is pretty simple, And would be great if its possible to avoid that.

Will be possible to do something in this way in a near future?

**Comment by JohnnyWestlake** [comment]
You can try setting and awaiting the source on the  SvgImageSource *before* setting it as the image source. It should avoid the flickering, tho you still won't get real time animation because of the asynchronous nature of that flow.

 (Though if you've got too much time on your hands you can drop down into Win2D levels and do it)

**Comment by samschiferl** [comment]
Thank you for your feedback. I work on the XAML team at Microsoft. We are aware of the issue and plan to improve SetSourceAsync in a future release so that the flickering no longer occurs.

In the meantime, you can workaround the issue by using two SvgImageSources and alternating the Canvas.ZIndexProperty of each one. On each frame you can call SetSourceAsync on the SvgImageSource that is lower in the z-order and then switch the two SvgImageSources to go to the next frame.

**Comment by juanpaexpedite** [comment]
Really thank you for the answer @samschiferl (hopefully not a Win2D workaround answer :)). 

I will try the workaround. Is there a roadmap or clue about SVG?.
I would like to implement a library to animate paths, strokes, etc. and one day something like Lottie with Composition, because I understand there is no roadmap for 'XAML stroke and path animation' on the way isn't it? 

Thank you..

**Comment by sohchatt** [comment]
@juanpaexpedite Support for stroke and path animations is on the [public backlog](https://developer.microsoft.com/en-us/windows/platform/features/animatedvectorgraphicssupportinthevisuallayer/): as discussed in #193, this is an area that is being investigated currently. This feature has been requested repeatedly and as soon as we have more clarity on actual timelines, we'll let you know.

**Comment by msftdavid** [comment]
It sounds like a workaround has been provided for this issue.
