### ISSUE TITLE
Expression animation stops when app is moved to another monitor with a different DPI

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#200]
I have noticed a potential bug where when I drag the app to another external monitor, my expression animation stops working until I manually re-enable it.

The expression animation basically syncs the `Button`'s position with the scroll position.
```
        private void SyncScrollingAndLoadMoreButtonPosition(ScrollViewer scrollViewer, Visual buttonVisual)
        {
            var scrollViewerPropertySet = scrollViewer.ScrollProperties();
            var syncScrollingAnimation = _compositor.CreateExpressionAnimation("ScrollViewerPropertySet.Translation.Y");
            syncScrollingAnimation.SetReferenceParameter("ScrollViewerPropertySet", scrollViewerPropertySet);
            buttonVisual.StartAnimation("Offset.Y", syncScrollingAnimation);
        }
```

The workaround is to subscribe to `DisplayInformation.GetForCurrentView().DpiChanged` and call the above method again.

This occurs in build/SDK _14393_.

**Comment by likuba** [comment]
Hey @JustinXinLiu 
Unfortunately, I think this is actually another manifestation of where properties that are shared between Composition & XAML Layout don't play nice on 14393 (https://github.com/Microsoft/WindowsUIDevLabs/wiki/XAML-Composition-Interop-Behavior-Changes).   When DPI changes, the logic run by the framework is effectively the same as a window size change.  Even though you don't physically see the window change size, Windows is doing some virtualization on behalf of the app that runs the same logic and would trigger layout to run (in this case, setting an offset that breaks the binding for your expression).  In the workaround above where you are  specifically addressing DPI change, I suspect you may also hit cases where you see issues in other window resize scenarios.  To robustly fix this on 14393 you will likely need to use the Canvas workaround we've talked about in other threads.  On post 14393 builds there is a better workaround, but my assumption is that you are looking for your app to run on the last released build, not just insider/vNext :)

**Comment by JustinXinLiu** [comment]
@likuba ohhh right!

Yeah unfortunately I will have to use the current workaround as we have to support _14393_. But at least it's working so I am not too concerned about it. Just wonder if the new workaround is documented anywhere?

Thanks!

**Comment by likuba** [comment]
Cool glad we got it figured out :)
@sernaj is there any documentation up for the new interop policy yet?

**Comment by sernaj** [comment]
We don't have the new stomping fix officially documented yet, but that's coming in the next few weeks along with a sample. Here's a quick synopsis of it so you can try this out now on any recent fast track insider build (15043 or later.) 

You can now use ElementCompositionPreview to inject a Translation property into the PropertySet of the Visual you're working with for example:

      ElementCompositionPreview.SetIsTranslationEnabled(myInteropVisual, true);

This adds a translation property to the propertyset that can be used like Offset. Strongly recommend giving it a value on first use to avoid creation timing problems so that it's ready when you need it. For example:

       var myInteropVisualPropertySet = ElementCompositionPreview.GetElementVisual(myInteropVisual).Properties;
       myInteropVisualPropertySet.InsertVector3("Translation", Vector3.Zero);

Then you can use Translation like Offset. Love to hear your feedback if you try this out. We think this will be easier as it lives with ElementCompositionPreview and doesn't make you add elements to your mark up.

**Comment by JustinXinLiu** [comment]
Nice! I will definitely try it out and let you know. Cheers. @sernaj

**Comment by sernaj** [comment]
Awesome, definitely let us know what you think.
