### ISSUE TITLE
System crash due to ExpressionAnimation

### ISSUE THREAD

**Issue by cyrilcathala** [Microsoft/WindowsUIDevLabs#23]
Hi,

I'm using an expression that crashes Windows on PCs without dedicated graphic cards. The bug occurs on build 10586, I haven't tested on the latest Windows Preview.

Here is the expression animation:
`( (ScrollManipulation.Translation.X > -100) ? 0 : (Lerp(0, -100, Clamp(-ScrollManipulation.Translation.X / MaxScroll, 0,1))) )"`

To fix it, I had to use a more verbose version:

`( (ScrollManipulation.Translation.X > -100) ? (0): Lerp(0,-100, (    ((-ScrollManipulation.Translation.X / MaxScroll)<0)?0: ((-ScrollManipulation.Translation.X / MaxScroll)>1)?1: (-ScrollManipulation.Translation.X / MaxScroll) )       ) )"`

Is the ternary operator compatible with imbricated functions? Is it a known issue?
I know about the issue #19 but I didn't manage to fix it just by adding parenthesis.

**Comment by pgills** [comment]
Thanks for the find @cyrilcathala. I'm adding @patsiu who has been tracking issues associated with #19.

Hopefully this is a duplicate.

**Comment by patsiu** [comment]
Hi @cyrilcathala,

I believe you may be hitting what was found in Issue #19. However, simply adding more parenthesis does not necessarily solve the issue. Can you try the following for me to confirm this is the case?

In your ternary operator, add in your condition portion a sequence of nested 0's such as [...] + (0 + (0 + (0 + (0 + (0+0))))). (The more complex your "if true" and "if false" portions are, increase the number of nested 0's in the condition). Thus your ternary will look something like A > x + 0 + (0 + (0 + (0 + (0 + (0+0))))) ? B + C: D + E.

If this is the same issue, it is fixed on the latest insider build, but since you mentioned you are on 10586, try this out and let us know what happens.

**Comment by pgills** [comment]
Closing. If you are still hitting that issues please reactivate. Thanks!
