### ISSUE TITLE
ShyHeader doesn't fit page width

### ISSUE THREAD

**Issue by pcolmer** [Microsoft/WindowsUIDevLabs#232]
Is there a reason I'm missing as to why the content of the ShyHeader sample is restricted to a width of 1050? If I want to use that in my own app, am I OK to remove the width specification?

**Comment by likuba** [comment]
There is no significance to that particular number--you should be able to adjust the width as you see fit (as long as OverlayRectangle and BackgroundRectangle are the same width as each other).  In the C# file it just references the width of the rectangle:

```
            // Create a Visual for applying the blur effect

            _blurredBackgroundImageVisual = _compositor.CreateSpriteVisual();

            _blurredBackgroundImageVisual.Brush = blurBrush;

            _blurredBackgroundImageVisual.Size = new Vector2((float)OverlayRectangle.ActualWidth, (float)OverlayRectangle.ActualHeight);
```
There is also already a handler that should accommodate the page changing sizes, but let us know if you seem to hit any issues adjusting the header size.


```
        private void Page_SizeChanged(object sender, SizeChangedEventArgs e)

        {

            if (_blurredBackgroundImageVisual != null)

            {

                _blurredBackgroundImageVisual.Size = new Vector2((float)OverlayRectangle.ActualWidth, (float)OverlayRectangle.ActualHeight);

            }

        }
```

**Comment by pcolmer** [comment]
Thank you for the reply.

Looking at the XAML in more detail, the top-level "view" is something like this:

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Grid>
            <ScrollViewer x:Name="MyScrollviewer">
                <Grid>
                    <Grid Grid.Row="1" x:Name="SquareGrid" />
                    <Grid x:Name="Header" />
                </Grid>
            </ScrollViewer>
        </Grid>
    </Grid>

Clearly simplified :)

My thoughts are:

- There are no row definitions in any of the grids, so Grid.Row="1" would seem to be redundant?
- Do we need Grid, Grid, ScrollViewer? Can we eliminate that second Grid?
- Can we use StackPanel anywhere so that the BackgroundRectangle and OverlayRectangle can be locked to the sides of the StackPanel?

I'll try to do some experimentation. I was just thinking that it might be possible to simplify the XAML a little bit ...

**Comment by likuba** [comment]
Thanks for the feedback :) If you do find a way to simplify the markup, you should feel free to submit a pull request so that it is fixed for posterity. 

As for the specific thoughts: 

- For Grid.Row = "1" this seems like it was an artifact I just didn't clean up, so fair point :)
- The extra Grid was added to deal with one of the seams in XAML-Composition Interop in build 14393 where Layout & animating Offset could "clobber" each other (discussed [here](https://github.com/Microsoft/WindowsUIDevLabs/wiki/XAML-Composition-Interop-Behavior-Changes)).  If you aren't trying to get this experience on 14393 you could eliminate the extra Grid and leverage the new Transform property (sample [here](https://github.com/Microsoft/WindowsUIDevLabs/tree/master/SampleGallery/Samples/SDK%2015063/OffsetStompingFix)).
- Not sure on the StackPanel suggestion--as I mentioned above definitely open to suggestions 👍

**Comment by msftdavid** [comment]
Sounds like the original question has been answered, so closing this issue. Thank you for your feedback. Feel free to submit a pull request for any improvements to samples!
