### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by csnazell** [Microsoft/WindowsUIDevLabs#25]
Windows.UI.Composition seems to have adopted the same laissez-faire attitude to documenting how it works as the rest of UWP. The MSDN documentation is merely a regurgitation of the APIs with an occasional remark throw in and not much else. The overview documentation is very shallow and doesn't address the core fundamentals of how composition works.

It's in stark contrast to Apple's documentation on Core Animation. The [Core Animation Programming Guide](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/CoreAnimation_guide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004514-CH1-SW1) provides an excellent walk through of the concepts underlying the API, how it integrates with the higher level user-interface APIs  and how a developer works utilises Core Animation.

Please review Apple's documentation and produce something similar. A couple of MSDN articles and some non-real world sample projects aren't acceptable.

**Comment by pgills** [comment]
Thanks. We're currently investigating new ways to deliver reference documentation, overview information, code examples, and conceptual content.

Which types of content would you prefer to see more of as we continue to iterate on our APIs:

1. Long form static textual/visual content covering conceptual material - similar to what you've suggested
2. Textual content explaining the concepts leveraged within the context of an interactive code sample
3. Video content covering conceptual material
4. Video content covering concepts leverages within the context of an interactive code sample
5. "How To" content (textual, video, or both) that focuses on how achieve a common UI pattern using the API

I'd like to open this up to @tomzorz and @JustinXinLiu as they have been consistently piloting and providing good feedback on the APIs.

**Comment by tomzorz** [comment]
_Thanks for the ping :)_

I'd say that to start out a more in-depth doc would be nice, akin to the Core Animation docs. Other than that what I think would be most helpful is the following: combine the points 2, 4 and 5. Start with a textual / short video explanation of a core concept, than pivot to some actual uses in real apps supported with a complete project sample and a detailed video tutorial of building that from the ground up.

In my experience people are usually quick to embrace new APIs - especially with a good introduction, and the samples + videos would show them _where_ and _how_ to use them. (Also, I really like see docs telling us the _current limitations_, and what _not to do_ including explanations. These usually really help clarify things.)

**Comment by JustinXinLiu** [comment]
Personally I LOVE the samples provided by you guys. It's very hard to just go through the API list and understand how powerful they are. But with cool samples like the *continuity* or *z-order scrolling*, people can see how capable they are and then they are more likely to dig into the APIs and build up their ideas.

Of course if we could have better documented APIs it would always be welcome. I really like the *motion design* listed on this [page](http://getmwf.com/styles/motion.html) from Microsoft. Short and sweet Gifs plus some sample code would be really cool!

**Comment by cyrilcathala** [comment]
The samples are good to see what the APIs are capable of. But honestly, first time I digged into the Z-Order scrolling sample I was like "whaaat? there is so much code, it seems really complex". Well, that was before I get used to the API and all :)

Anyway, I'd vote for 5/HowTos. It's a good way to have both an example and explanations to get into the API. Maybe with GIFs and "wow effects" as suggested by @JustinXinLiu. 
Obvisouly, a documentation explaining the overall concepts is a must have. CoreAnimation doc is fine and a good example.

One more thing: I might be speaking for myself here, but I think there need to be more XAML interop doc and complex samples. It's quite difficult to achieve a perfect sync during transitions, you have to play with opacity and visibility right now, but some examples might be nice.

**Comment by csnazell** [comment]
I'm not a big fan of samples as they tend to be limited by the imagination and experience of the person writing them, don't provide much insight into the "system" the API represents and tend not to be particularly applicable in the real world. 

For example the continuity sample passes unserialisable data in the navigation parameter which would cause navigation history serialisation to crash. A real-world implementation would have to do something along the lines of sub-classing Frame and using the navigation event system to obtain visuals from the outgoing page and hand them off to the incoming one, triggering any necessary animation between the two.

When I'm documenting APIs for clients my general rule of thumb is "Physics, Chemistry, Biology, Petting Zoo":

_Physics_: atomic building blocks, their life-cycles & modes of interaction

_Chemisty_: composition of building blocks into simple forms that demonstrate the basics

_Biology_: composition of simple forms into complex forms that would add polish to an app

_Petting Zoo_: a small collection of illustrative real-world samples that are well commented  

As long as the documentation imparts understanding in a clear and concise fashion I'm not picky as to how it does so. Whilst some animations & videos could be illustrative I would have thought that they'd be significantly more costly to maintain but that's up to you guys.

**Comment by juanpaexpedite** [comment]
a great power requires a great responsibility... I know it is just the beginning of Composition and in the future who knows could be released the 'Compositor Blend Expression Designer' :). I always forget everything about matrix and would be great have some tutorial on how to fight with that. I am making some experiments rotating cards and look really awesome and smooth with Composition but I am just copying pasting from https://github.com/Microsoft/composition/issues/22 because I do not really know what I am doing. But no hurry first the Build then let's delete all our obsolete code :) and began again.

**Comment by assassin316** [comment]
When will the new updates to Composition be documented in MSDN??

**Comment by sernaj** [comment]
All of the new Windows.UI.Composition bits released for //build this week are preliminary versions of the final APIs that were pulled into a preview insider release. We are done with the final version and you can expect to get those bits in the next fast ring insider build. Those are the APIs we will be documenting for MSDN. Expect those docs to be final and land with the formal full release. But we are committed to helping you out and answering questions as you have them as our insiders are super important to us.

**Comment by aL3891** [comment]
i'd also like better and more discoverable docs for this, especially the expression system since its based on strings and thus even less discoverable via reflection and such. if you're not able to deliver docs on msdn when you drop a new windows sdk, please atleast document it somewhere, either in the sdk itself or on github.

**Comment by assassin316** [comment]
Yes I completely agree with you, the expression system definitely needs more documentation. I currently have no clue what properties I can animate in an expression since no intellisense exists and not much docs available. Also new values such as this.StartingValue, this.FinalValue, etc.  have been introduced at Build and hope to see more info on such features.

**Comment by tomzorz** [comment]
Yeah well the intellisense situation should be better if the expressions were strongly-typed instead stringly-typed :)

**Comment by aL3891** [comment]
I can see why they did that though, makes the javascript and c++ story a lot easier i suppose.. still a spec would be nice :) https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.composition.expressionanimation.aspx and https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.composition.compositionobject.startanimation.aspx has some info but its rather unclear if that has been updated even for the november update.. 

I've actually been thinking about a expressiontree based helper library for expressions, it should be able to do most of the heavy lifting. is anyone working on something similar in the team? @pgills

**Comment by tomzorz** [comment]
@aL3891 Yeah, I started working on that a while back but I haven't produced anything usable yet. (I've been completely swamped in other things :disappointed: )

**Comment by aL3891** [comment]
All right, i might take a stab at it then, it should be able to do the expression string generation and possibly also adding the needed parameters

**Comment by tomzorz** [comment]
@aL3891 All right. If you feel like collaborating on [this library](https://github.com/tomzorz/Finch) shoot me a mail: tomzorz at outlook dot com - I'd be happy to work with someone on this. :+1:

**Comment by pgills** [comment]
@aL3891 @tomzorz folks on the team have been investigating ways help improve the developer workflow around expressions. Personally, have written little Expression helpers for some of the demos I've built and I know others on the team have as well. Mostly, purpose built, not generalized. So it's definitely a known issue on the team.

So to recap on the suggestions (this is good data folks):

1. More comprehensive documentation on Expressions 
2. Have documentation line up with the SDKs (MSDN, maybe GitHub for Insider flights, or at least pointers)
3. Folks are really interested improving the developer experience when using expressions
 1. Some form of Intellisense improvement
 2. An Expression helper for common usage in code rather than in strings (think normalization, parallax, etc.)

**Comment by aL3891** [comment]
@pgills Sounds good, i was thinking about writing a more general one, but i was wondering if you had something like that already in progress, but it sounds you don't have any firm plans for that at the moment?

**Comment by tomzorz** [comment]
@aL3891 Well we could probably skip the expression trees, and instead focus on writing helpers for common scenarios: parallax, normalization, meta-values (like startingvalue), branching.

**Comment by aL3891** [comment]
I think both are useful, but a general expression tree based api for generating composition expressions would make those scenarios a lot easier to implement "yourself", and it would also serve as an inline reference for the composition expressions them selves. 

Again, i'm not asking the team to drop what they're doing and implement that, i'm just asking if they're already working on it so we can avoid duplicate libraries

**Comment by assassin316** [comment]
Aside from expression documentation, do you think that eventually there will a way to debug an expression, for example, outputting values to the Output window as they change ???  this would also be very helpful, especially in cases where expression strings become complicated.

**Comment by pgills** [comment]
@aL3891 Currently, we don't have plans to release a generalized expression helper for generating expressions so there's no potential duplication at this time. However, the team is definitely looking at improving the experience with expressions.

@assassin316 I've edited my above comment to capture your feedback.

**Comment by patsiu** [comment]
Going to chime here and build upon what @pgills started earlier... 

We know we have a couple of hurdles to get over in order to make Expression Animations A LOT easier to use, some of which you guys have highlighted already. Trust me when I say we’ve run into a number of these ourselves :). That said, we are currently in the process of looking into the following issues for Expressions in the following order (and weighing them against other enhancements for the platform):

1.	Improving the documentation around Expression animations so it’s a lot clearer on what you can use within the Expression string and how the different pieces fit together. 
2.	Improving the overall experience with authoring Expressions in Visual Studio to make it easier to know you’re creating a valid expression before compile and runtime
3.	Improving how to more effectively diagnose/debug in Visual Studio to see why a valid expression is not outputting the correct values

Does the order of the list sound right to folks? Align with the current issues you are facing when using Expressions? Are there other issues you guys feel are more important?

**Comment by aL3891** [comment]
@pgills Allright cool, i'll be sure to ping you guys when i have something useful, i'd love to get you feedback as well since you have the best insight in to the corner cases

@patsiu That sounds good(to me atleast), allthough i might actually but debugging above the authoring, since the community can write apis to help out with the authoring, but we cant really help with the debugging or docs.

**Comment by tomzorz** [comment]
@patsiu yup, seems to be in order :)

**Comment by aL3891** [comment]
I've got an initial version of my library for writing expressions as lambdas online, check it out over at https://github.com/aL3891/CompositionAnimationToolkit

**Comment by JohnnyWestlake** [comment]
As an extra, could we get some pointers around which objects we should / shouldn't dispose? Nearly everything implements IDisposable around this API, but I gather a lot of them we shouldn't call Dispose on, like ScrollViewers CompositionPropertySets, Element backing Visuals, etc.

Would be nice to know, as for example, if I apply an InsetClip too an Element's backing Visual, do I have to Dispose the clip when I'm done with it?

**Comment by sernaj** [comment]
@JohnnyWestlake - sorry for the delayed response this topic morphed from docs to general questions and we lost tracking on it. No, you don't need to call dispose on an InsetClip. While we have Dispose implemented throughout the API it more important in scenarios where you are building pure composition content in an "island" rather than using backing Visuals from XAML UIElements. I'm going to mark this as closed - if you want more guidance on Dispose, go ahead and open a new issue for that and we'll jump on it.
