### ISSUE TITLE
Misposition of border when applied RotationAxis

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#32]
I am experimenting with just the following control, to create a Card flipping effect.

<UserControl  mc:Ignorable="d" Width="236" Height="360" >

    <Grid Width="236" Height="360">
        <Border x:Name="Back" Padding="0" BorderBrush="DarkGray" BorderThickness="2" CornerRadius="20" Background="Orange" 
                VerticalAlignment="Stretch" HorizontalAlignment="Stretch">
        </Border>
        <Border x:Name="Front" Padding="0" BorderBrush="DarkGray" BorderThickness="2" CornerRadius="20" Background="Red" 
                VerticalAlignment="Stretch" HorizontalAlignment="Stretch">
        </Border>
    </Grid>
</UserControl>

And I set the composition like the following:

 private void InvalidateComposition()
        {
            float halfwidth = (float)(Width / 2.0);

            FrontVisual = CompositionManager.GetContainerVisual(Front);
            FrontVisual.RotationAxis = new Vector3(0, 1, 0);
            FrontVisual.CenterPoint = new Vector3(halfwidth, 0f, 0f);
            FrontVisual.BackfaceVisibility = CompositionBackfaceVisibility.Hidden;

            BackVisual = CompositionManager.GetContainerVisual(Back);
            BackVisual.RotationAxis = new Vector3(0, 1, 0);
            BackVisual.CenterPoint = new Vector3(halfwidth, 0f, 0f);
            BackVisual.BackfaceVisibility = CompositionBackfaceVisibility.Hidden;

...
        }
Doing that if I take a look to the Live Visual Tree, the front border is positioned top 360 px of the back border not over ("z-order"), might be I am doing something wrong.
This makes that if I add more instances they are overlapped one over another so I cannot make the use of tap events, etc.

**Comment by robmikh** [comment]
Hi juanpaexpedite!

You're correct in that changing the transform doesn't change the order of either the visuals or the UIElements in the tree. This means during a hit test, Front will always report that it was hit while Back never will. One way you could get around this is with the following:

I modified your snippet to rotate both borders when a button is clicked, very much like a card. First I added a button to your XAML:

```
<Grid x:Name="MainGrid" Width="236" Height="360" Loaded="MainGrid_Loaded">
    <Border x:Name="Back" Padding="0" BorderBrush="DarkGray" BorderThickness="2" CornerRadius="20" Background="Orange" 
            VerticalAlignment="Stretch" HorizontalAlignment="Stretch"  />
    <Border x:Name="Front" Padding="0" BorderBrush="DarkGray" BorderThickness="2" CornerRadius="20" Background="Red" 
            VerticalAlignment="Stretch" HorizontalAlignment="Stretch"  />
</Grid>

<Button HorizontalAlignment="Right" VerticalAlignment="Bottom" Content="DebugButton" Margin="0, 0, 15, 15" Click="Button_Click" />
```

As you can see, I also added an event handler to MainGrid's Loaded event that sets up our perspective transforms:

```
private void MainGrid_Loaded(object sender, RoutedEventArgs e)
{
    InitComposition();
}

private void InitComposition()
{
    //
    // Set up our perspective trasnform on the parent
    //
    var parent = ElementCompositionPreview.GetElementVisual(MainGrid);

    float depth = 500.0f;
    var projectionMatrix = new Matrix4x4(1, 0, 0, 0,
                                         0, 1, 0, 0,
                                         0, 0, 1, -1 * (1 / depth),
                                         0, 0, 0, 1);

    var perspectiveMatrix = Matrix4x4.CreateTranslation(0, -100.0f, 0) *
                            projectionMatrix *
                            Matrix4x4.CreateTranslation(0, 100.0f, 0);

    parent.TransformMatrix = perspectiveMatrix;


    //
    // Make sure the two card faces start in the right position
    // and have the proper CenterPoint and RotationAxis.
    //
    float halfWidth = (float)(Front.ActualWidth / 2.0);
    float halfHeight = (float)(Front.ActualHeight / 2.0);

    var frontVisual = ElementCompositionPreview.GetElementVisual(Front);
    frontVisual.RotationAxis = new Vector3(0, 1, 0);
    frontVisual.CenterPoint = new Vector3(halfWidth, halfHeight, 0f);
    frontVisual.BackfaceVisibility = CompositionBackfaceVisibility.Hidden;
    frontVisual.RotationAngleInDegrees = 0.0f;

    var backVisual = ElementCompositionPreview.GetElementVisual(Back);
    backVisual.RotationAxis = new Vector3(0, 1, 0);
    backVisual.CenterPoint = new Vector3(halfWidth, halfHeight, 0f);
    backVisual.BackfaceVisibility = CompositionBackfaceVisibility.Hidden;
    backVisual.RotationAngleInDegrees = 180.0f;
}
```

The first portion ensures that we have a perspective matrix ready on the parent Visual (which is the MainGrid). Without the projection matrix, the card flipping effect wouldn't look quite right, as everything would be an orthographic projection instead of having a perspective. Next, we set the RotationAxis, CenterPoint, BackfaceVisiblity, and RotationAngle for each side very much as you have in your code. Note that I changed your code to make sure that the center point is in the center of the card to make it look like it was flipping in place. If that wasn't your intention, keeping it as you have it should work.

But before we jump into the next bit, do note that I added to member variables to the page:

```
bool _isRedSideUp;
bool _isAnimating;

public MainPage()
{
    this.InitializeComponent();

    _isRedSideUp = true;
    _isAnimating = false;
}
```

I'll explain those later. Now we finally hook up the event and animation:

```
private void Button_Click(object sender, RoutedEventArgs e)
{
    Animate();
}

private void Animate()
{
    if (!_isAnimating)
    {
        var frontVisual = ElementCompositionPreview.GetElementVisual(Front);        
        var backVisual = ElementCompositionPreview.GetElementVisual(Back);

        float frontStart = _isRedSideUp ? 0.0f : 180.0f;    
        float frontEnd = _isRedSideUp ? 180.0f : 0.0f;

        float backStart = _isRedSideUp ? 180.0f : 360.0f;        
        float backEnd = _isRedSideUp ? 360.0f : 180.0f;

        var compositor = frontVisual.Compositor;
        var batch = compositor.CreateScopedBatch(CompositionBatchTypes.Animation);
        var frontAnimation = compositor.CreateScalarKeyFrameAnimation();

        frontAnimation.InsertKeyFrame(0.0f, frontStart);
        frontAnimation.InsertKeyFrame(1.0f, frontEnd);

        frontAnimation.Duration = TimeSpan.FromMilliseconds(3000);
        frontAnimation.IterationCount = 1;

        frontVisual.StartAnimation("RotationAngleInDegrees", frontAnimation);

        var backAnimation = compositor.CreateScalarKeyFrameAnimation();

        backAnimation.InsertKeyFrame(0.0f, backStart);
        backAnimation.InsertKeyFrame(1.0f, backEnd);

        backAnimation.Duration = TimeSpan.FromMilliseconds(3000);
        backAnimation.IterationCount = 1;

        backVisual.StartAnimation("RotationAngleInDegrees", backAnimation);

        batch.Completed += (o, i) =>
        {
            _isRedSideUp = !_isRedSideUp;
            _isAnimating = false;
        };

        batch.End();
        _isAnimating = true;
    }
}
```

What this does is animate both the Front and Back at the same time, but animates them in different ways. If Front is currently facing up (the red side) then Front should start at 0 degrees and animate to 180, where it will be hidden, and opposite if Front is facing down. Same with Back, but we start at 180 so it is hidden at first and animate to 360 to it moves in the same direction as Front but reveals itself instead of hiding. The important part of this is using a batch to know when the animation has ended. When the animation is complete, we note which side is now facing up. We also have a bool rigged up to make sure that we don't try to animate them again until the current animation has completed.

That same bool that tells you which side is up can now be your hit-test. If you listen to the Tapped event on MainGrid, you can check the bool to see which side is up and thus logically which side received the input. Another way is that you could turn off hit testing on Front when an animation ends and Front is no longer facing up, and turn it back on when it is. That way you could use two different event handlers directly on Front and Back.

The end result should look like this:

![Image of Card Flipping](https://media.giphy.com/media/5sTJYjB8JYsVi/giphy.gif)

Let me know if you have any questions!

**Comment by juanpaexpedite** [comment]
Thanks a lot, this  frontVisual.CenterPoint = new Vector3(halfWidth, halfHeight, 0f); did the trick! Understood. Composition is really really smooth, I love that.

**Comment by pgills** [comment]
Closing. Thanks for the explanation @robmikh.

**Comment by XamlFlair** [comment]
Hi @robmikh, I have a quick question concerning your code:

    float depth = 500.0f;
    var projectionMatrix = new Matrix4x4(1, 0, 0, 0,
                                         0, 1, 0, 0,
                                         0, 0, 1, -1 * (1 / depth),
                                         0, 0, 0, 1);

    var perspectiveMatrix = Matrix4x4.CreateTranslation(0, -100.0f, 0) *
                            projectionMatrix *
                            Matrix4x4.CreateTranslation(0, 100.0f, 0);

    parent.TransformMatrix = perspectiveMatrix;

Would applying this matrix work for both x-axis and y-axis rotations? In other words, is the perspective view supposed to be centered for both axis' ?? I'm asking because I can't get it to work for both. Rotating on the x-axis for me doesn't center the perspective view. I have an question for this: #339

**Comment by assassin316** [comment]
Hi @robmikh, I have a quick question concerning your code:

    float depth = 500.0f;
    var projectionMatrix = new Matrix4x4(1, 0, 0, 0,
                                        0, 1, 0, 0,
                                        0, 0, 1, -1 * (1 / depth),
                                        0, 0, 0, 1);

    var perspectiveMatrix = Matrix4x4.CreateTranslation(0, -100.0f, 0) *
                            projectionMatrix *
                            Matrix4x4.CreateTranslation(0, 100.0f, 0);

    parent.TransformMatrix = perspectiveMatrix;

Would applying this matrix work for both x-axis and y-axis rotations? In other words, is the perspective view supposed to be centered for both axis' ?? I'm asking because I can't get it to work for both. Rotating on the x-axis for me doesn't center the perspective view.

I have an open question for this: **#339**
