### ISSUE TITLE
Which has a better performance for scaling a viewbox or Composition?

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#33]
Suppose we have a Canvas and inside it has elements as usual. I can easily place the canvas inside a Viewbox and I have it scaled right according with the Window Size.

From the Composition pov, is there a way to make scaling of a control, might be only hardcoded, and the performance will be times better than using a ViewBox?

**Comment by tomzorz** [comment]
Interesting question - I think you could measure that with the current perf tools. Just create a complicated layout (e.g. 5000 rectangles in a grid), and recreate/resize it + measure the time it took for it to render completely. 

Although if you transform your content with composition you'll lose some/most of the interaction events due to the current state of the Xaml interop.

**Comment by pgills** [comment]
Yes this is very interesting question. We haven't investigated specifically in this area regarding this exact scenario.

I believe you could make a custom control that's Windows.UI.Composition based...

A couple of questions:
1. Are there cases where you are seeing issues with current usage of `Viewbox` in performance?
2. Are there other aspects of `Windows.UI.Composition` you'd like to incorporate that is leading you to make a custom control?
3. Are you just curious?

And to @tomzorz point, as soon as you start going down this path you'll need to implement more functionality, which is why I'm interested in where `Viewbox` isn't meeting your current needs.

**Comment by juanpaexpedite** [comment]
At this moment is more a curiosity than an issue I have. Because I think Composition will have enough performance working inside a Viewbox with a normal amount of controls. I thought about this because I did a minigame (AnimalCards) in the Windows 8 days :).  and when it contains plenty of controls sometimes it had a low performance using translationX,Y in low spec tablets. 

My technical doubt is more how a Viewbox and Composition are related, I mean the scaling of the Viewbox is internally made by its Visual and Compositor or goes directly to a deeper Layer?

**Comment by pgills** [comment]
@juanpaexpedite Unfortunately, I don't have the expertise either with regards to how Viewbox is internally built. If you start seeing performance hiccups with Viewbox let us know, but as we said before right now talking directly to Composition will trade off nice control features in Viewbox if you do it yourself.

However, we continuing to improve our integration of Composition with XAML and we are definitely keeping performance in mind.

I'm going to close this issue since we're just curious on the subject, if you start seeing issues either file a new issue or reactive this one. Thanks for playing with the API though we are loving the feedback!
