### ISSUE TITLE
Conditional use

### ISSUE THREAD

**Issue by ktd12** [Microsoft/WindowsUIDevLabs#48]
I am updating my uwp app to use the visual layer in select places.  The target platform min Version is 10240, so I need to conditionalize the use of the visual layer.  Please add an example of how to do  this to one of your samples or user documentation.  Here is what I am currently doing to accomplish this:

 if ( Windows.Foundation.Metadata.ApiInformation.IsMethodPresent("Windows.UI.Xaml.Hosting.ElementCompositionPreview", "GetElementVisual") )
            {}

**Comment by pgills** [comment]
@ktd12 Yes we are definitely looking at developing a sample for fallback.

There's a spectrum of conditions to incorporate when thinking about fallback and they can be unique to each application so there isn't a one size fits all solution unfortunately.

Here are some aspects to consider:

1. The basic availability of the Composition API
  1. E.g. If `ElementCompositionPreivew.GetElementVisual` is present which you call out
2. If it's present, the availability of a specific feature within the Composition API
  1. E.g. Drop shadows are only available on builds greater than 10586
3. The availability of Effects per build
  1. E.g. GaussianBlur is only available on builds greater than 10586, however it can be defined at author time on lower builds, it just won't be available at run time.

So depending on the specific usage of the API will influence how you perform your fallback.

Thanks for the feedback, as we really appreciate it because we want to know what our developers want to see!

**Comment by ktd12** [comment]
Great, Thanks.  By the way, your API is really awesome and easy for a XAML developer to use.  It was your sessions at Build 2016 that got me to take a look at the Composition API.   FYI, I am changing the uwp app Visual Timers so that it scales a sprite instead of resizing a xaml rectangle (which is much better because the animation doesn't run on the UI thread).
