### ISSUE TITLE
Custom strongly typed property sets

### ISSUE THREAD

**Issue by aL3891** [Microsoft/WindowsUIDevLabs#52]
Hello there, 
I have a question about property sets. Currently, getting things out of a property set involves calling one of the `TryGet*` Methods that takes an out parameter. Is the reason for not having a single overload or throwing is because of compatibility with the other Uwp languages? 

I made a small extension method for getting values directly since i cant use out parameters in a c# expression, but it would be nicer to be able to create your own subclasses of `CompositionPropertySet ` with strongly typed properties. So my main question is, is there anything special going on with `CompositionPropertySet `(or `CompositionObject`) that has to be done in order to make a property animatable? Like registration similar to dependency properties or something like that. Or is it just a regular property? I tried to do some reflecting but i cant see past the winmd files :/ I assume its possible somehow since i suppose that is what the `Insert*` methods are doing.

**Comment by aL3891** [comment]
Looking into this a bit more this doesnt seem possible at the moment, `CompositionPropertySet` is sealed, since its a WinRT class but `CompositionObject` doesnt seem to have a public constructor, there doesn't seem to be any deriving from that either.. Is there a particular reason that is not allowed?

**Comment by robmikh** [comment]
The reason why creating your own CompositionObjects isn't allowed is the unique way the Composition API is structured, which has to do with one of its strengths. The reason we are able to render everything quickly and efficiently yet still providing a flexibility of options is because all the work is done in the system compositor, the DWM. However in order to do that, there needs to be a communication mechanism between a user's application and the compositor process. This communication mechanism is the API itself. Most objects created with the API are tracked by the application and the DWM. This is nearly the same architecture used in the v1 of the composition API named Direct Composition (although the entire system has been evolving over time). You can read more about the basic ideas of the architecture [here](https://msdn.microsoft.com/en-us/library/windows/desktop/hh437350(v=vs.85).aspx). Note that the article is still in reference to Direct Composition, but it is still an interesting read.

**Comment by aL3891** [comment]
I see, thanks for the link!
I do think there is value in having statically typed properties though, but i think i can do that with a wrapper class that you can derive from. That could also be a place to put setter methods, since at the moment it seems like the only way to change a value in a propertyset is to animate it. (right?)

**Comment by robmikh** [comment]
You should be able to call Insert again using the same name it should update the value without having to write an animation. Thanks for the feedback, we'll keep it in mind!

**Comment by aL3891** [comment]
ah, cool :)
