### ISSUE TITLE
Lambda expressions

### ISSUE THREAD

**Issue by aL3891** [Microsoft/WindowsUIDevLabs#59]
Allright, i've got an initial version of my library for writing animation expressions as lambdas! Check it over at https://github.com/aL3891/CompositionAnimationToolkit 
I'd love any feedback you might have!
cc @pgills @patsiu 

Using it you can for instance write something like this

    var propertySet = new
    {
        Rotation = 0,
        CenterPointOffset = new Vector3(redSprite.Size.X / 2 - blueSprite.Size.X / 2, redSprite.Size.Y / 2 - blueSprite.Size.Y / 2, 0)
    };

    expressionAnimation.ExpressionLambda(c => redSprite.Offset + propertySet.CenterPointOffset
        + c.Vector3(c.Cos(c.ToRadians(propertySet.Rotation)) * 150, c.Sin(c.ToRadians(propertySet.Rotation)) * 75, 0));

**Comment by ratishphilip** [comment]
Good work.
I am working on a similar concept of creating Expression animation using ExpressionTrees and Lambdas.

**Comment by pgills** [comment]
@aL3891 Interesting. We'll have some folks take a look!

**Comment by aL3891** [comment]
Cool!
Its now also on nuget: 
`Install-Package CompositionAnimationToolkit -Pre`

**Comment by ratishphilip** [comment]
@aL3891
cc @pgills @patsiu 
Check out my project [CompositionExpressionToolkit](https://github.com/ratishphilip/CompositionExpressionToolkit). I have optimized part of your code and added a Expression visitor which optimizes the parsing of the Lambda expression.

**Comment by aL3891** [comment]
Interesting @ratishphilip, i'll check it out. When you say optimized, are you referring to speed or expressiveness or something else?

**Comment by ratishphilip** [comment]
@aL3891 
In **CompositionPropertySetExtensions**
Instead of checking for each type specifically, I have used reflection to invoke the appropriate **CompositionPropertySet** method. This reduces the number of lines of code and also adapts automatically to future additions of **Insert*****xxx*** or **TryGet*****xxx*** methods in **CompositionPropertySet** for additional types. (Similar implementation has been incorporated for **CompositionAnimationExtensions**)

The **CompositionExpressionEngine** is based on the **ExpressionToken** class by Joseph Albahari. It provides a better method of visiting Expression Trees than the standard ExpressionVisitor. (It powers the expression visiting part in **LinqPad**!)

**Comment by aL3891** [comment]
I see, I've actually avoided reflection to make things easier for .net native :) I've been thinking about reducing allocations by using more stringbuilder but since i don't anticipate these methods to be call that frequently because of the reusability of animations, so its lower prio for me at the moment.

I've got some new updated coming that will also make using property sets a little easier, its in the repo but not up on nuget yet,

**Comment by pgills** [comment]
Added to Feedback milestone and cleaning up issues.
