### ISSUE TITLE
Question regarding CompositionPropertySet

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#66]
Why does **CompositionPropertySet** have a property called **Properties** of type __CompositionPropertySet__?

**Comment by patsiu** [comment]
Hey @ratishphilip,

CompositionPropertySet has this since it is derived from Composition Object which has a property called "properties" which is of type CompositionPropertySet. Note, that in the case where you create a CompositionPropertySet myPropertySet and reference it's "properties" property, we return myPropertySet.

**Comment by ratishphilip** [comment]
@patsiu Thanks for the reply. I needed the clarification for my [CompositionExpressionToolkit](https://github.com/ratishphilip/CompositionExpressionToolkit) which allows the use of lambda expressions to set the Expression value of ExpressionAnimation.
