### ISSUE TITLE
Offsetanimation only occurs on first item of CCC event

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#78]
Hi,

I am following the example for the ContainerContentChanging event to animate my gridview items upon loading. Each item does three animations just like in the Build 2016 Session: opacity scale and offset.

Here is my code:

`        private void AudioListBox_ContainerContentChanging(ListViewBase sender, ContainerContentChangingEventArgs args)
        {
            if (args.InRecycleQueue == false)
            {
               args.ItemContainer.Loaded += ItemContainer_Loaded;
            }

            args.Handled = true;
        }

        private void ItemContainer_Loaded(object sender, RoutedEventArgs e)
        {
            var itemsPanel = (ItemsWrapGrid)AudioListBox.ItemsPanelRoot;

            var itemContainer = (GridViewItem)sender;

            var itemindex = AudioListBox.IndexFromContainer(itemContainer);

            var uc = itemContainer.ContentTemplateRoot as Grid;

            var childPanel = uc.Children[0] as AudioGridItem;

            //Only animate visible items
            if (itemindex >= itemsPanel.FirstVisibleIndex && itemindex <= itemsPanel.LastVisibleIndex)
            {

                var itemVisual = ElementCompositionPreview.GetElementVisual(itemContainer);

                float width = (float)childPanel.RenderSize.Width;

                float height = (float)childPanel.RenderSize.Height;

                itemVisual.Size = new System.Numerics.Vector2(width, height);

                itemVisual.CenterPoint = new System.Numerics.Vector3(width / 2, height / 2, 0f);

                itemVisual.Scale = new System.Numerics.Vector3(1, 1, 1);

                itemVisual.Opacity = 0f;

                itemVisual.Offset = new System.Numerics.Vector3(50, 50, 0);

                //Create Animations
                KeyFrameAnimation offsetAnimation = _compositor.CreateScalarKeyFrameAnimation();
                offsetAnimation.InsertExpressionKeyFrame(1f, "0");
                offsetAnimation.Duration = TimeSpan.FromMilliseconds(550);
                offsetAnimation.DelayTime = TimeSpan.FromMilliseconds(itemindex * 30);

                Vector3KeyFrameAnimation scaleAnimation = _compositor.CreateVector3KeyFrameAnimation();
                scaleAnimation.InsertKeyFrame(0, new System.Numerics.Vector3(1f, 1f, 0f));
                scaleAnimation.InsertKeyFrame(0.1f, new System.Numerics.Vector3(0.05f, 0.05f, 0.05f));
                scaleAnimation.InsertKeyFrame(1f, new System.Numerics.Vector3(1f, 1f, 0f));
                scaleAnimation.Duration = TimeSpan.FromMilliseconds(500);
                scaleAnimation.DelayTime = TimeSpan.FromMilliseconds(itemindex * 30);

                KeyFrameAnimation fadeAnimation = _compositor.CreateScalarKeyFrameAnimation();
                fadeAnimation.InsertExpressionKeyFrame(1f, "1");
                fadeAnimation.Duration = TimeSpan.FromMilliseconds(2550);
                fadeAnimation.DelayTime = TimeSpan.FromMilliseconds(itemindex * 30);

                itemVisual.StartAnimation("Offset.Y", offsetAnimation);
                itemVisual.StartAnimation("Scale", scaleAnimation);
                itemVisual.StartAnimation("Opacity", fadeAnimation);
            }`

I have two questions:

If I set the args.handled to true, I don't see my items being loaded at all. When I remove the args.handled = true, the animations do occur. Is this supposed to be the correct behavior?

My second question: All the animations are run except for the offset animation. This only seems to affect my the first item that is rendered. I have checked that all code is executed for all items. Am I doing something wrong here ?

On a sidenote: I think the new composition API's are great and I hope to use them throughout my project.

Thanks

**Comment by pgills** [comment]
@AudioW For the second question, there have been some changes in the behavior around properties on the handoff Visual that are set by the app author and by the XAML framework - typically around properties that set by XAML layout. We're working on documenting that behavior. 

Here's the documentation for the Handled property: https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.containercontentchangingeventargs.handled.aspx

I'm unclear if that's the desired behavior or if it's just for event routing.

**Comment by likuba** [comment]
@AudioW 

The behavior change that @pgills mentioned is documented here: https://github.com/Microsoft/WindowsUIDevLabs/wiki/XAML-Composition-Property-Synchronization-Changes

If you are animating a property that XAML layout is setting it is "last one wins" so you need to make sure to run the animation after layout completes, or wrap the UI element in something like a canvas to prevent layout from breaking the animation binding.  Offset is the only property you are animating that conflicts with layout, so this is likely what you are hitting.

I'm not sure about the answer to your first question.  @JasterAtMicrosoft do you have any thoughts there?

**Comment by micahl** [comment]
When args.Handled = true the framework doesn't set the DataContext for the ItemContainer.  The implication is that any {Binding} in the DataTemplate won't evaluate to a result.  Depending on what you're doing that might mean things aren't visible or don't have a size or something else affecting the appearance.  When using the ContainerContentChanging event to progressively render the items in a list you can explicitly set the data values for elements in the inflated DataTemplate (see [ListView and GridView UI optimization](https://msdn.microsoft.com/en-us/windows/uwp/debug-test-perf/optimize-gridview-and-listview#update-listview-and-gridview-items-progressively)).  Basically, you can do your own data binding and if you're doing that then mark the event as Handled to let the framework know it can skip setting the DataContext (which does carry some additional cost).  On a related note, since the ItemContainers that are generated aren't removed from the UI tree as they're recycled you're only going to see the Loaded event fire at most once per container as you scroll and containers are re-used.  If the animation should be happening on everything in the list then you'll need to move that animation code from the Loaded event to happen in one of the phases for the ContainerContentChanging event when InRecycleQueue == false.  The initial phase is guaranteed.  Latter phases depend on whether there's time to execute which depends on how fast the user scrolls, the speed of the device, etc.

**Comment by AudioW** [comment]
Thank you for your replies. I still don't understand why only the first container in my listview is animated on the offset property and all the ones after are not. Is it possible for you to post a working sample that applies an offset animation to the listview items?

**Comment by AudioW** [comment]
Fixed in 14383 if you use itemvisual.contenttemplateroot instead of the container itself: this container is always being adjusted when the control is loaded so any offsets don't look properly: they adjust the item within the container.
