### ISSUE TITLE
Exposure wrong behavior

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#85]
I am applying the following image to the EffectEditor example with 14342 environment (SDK and Windows machine) and another 10586 environment (SDK and Windows).

![ellipse](https://cloud.githubusercontent.com/assets/5947026/15355732/6a92da0a-1cec-11e6-9f58-5fc9cd8ee205.png)

It just make the Exposure a bit in some pixels around the changes of color but not in general. I do not understand why the image does not get 'exposed'. Any idea? (I also tried with the same a jpg, but the same)

**Comment by pgills** [comment]
@juanpaexpedite Could you provide a short code snippet to help explain the issue a little more?

Thanks for the build/sdk configuration.

Is it that you are using the above image as a Source to the ExposureEffect?

**Comment by juanpaexpedite** [comment]
Simply replacing the code:

    m_noEffectBrush = CreateBrushFromAsset(
                //"Bruno'sFamily2015 (13)-X2.jpg",
                "ellipse.png",
                out imageSize);

in MainPage.xaml.cs of the EffectEditor example and then selecting Exposure from the combobox I move the slider.

**Comment by krenner** [comment]
@juanpaexpedite  The pixel intensity of this image is high so bumping up the exposure has little visual impact.  Setting the ExposureEffect Exposure property to -2 has impact. ![exposure](https://cloud.githubusercontent.com/assets/14005577/16065611/3ce0702e-3261-11e6-8ce8-e3a7da8f7e69.png)
 Using an image with less intensity will have better results.  There is a good demonstration of the ExposureEffect in the build talk, [Motion & Effects: A Deep Dive on How to Create Beautiful UX That is Worthy of 5 Stars ](https://channel9.msdn.com/Events/Build/2016/B830)  (skip to 48:00)
Thanks for all your feedback with the effects system and let us know if you have more questions.

**Comment by juanpaexpedite** [comment]
The following screenshot is my idea about how the exposure should go towards white more than just get saturated. Of course the definition could change, but would be great having a boolean to get the exposure effect work like the Adobe one:

![exposure_ape](https://cloud.githubusercontent.com/assets/5947026/16070437/4b248816-32cd-11e6-8c00-cd400fb6bac0.jpg)

Thank you for the reply

**Comment by MrTrillian** [comment]
The behavior you get with the Windows.UI.Composition API is the same you would get by drawing your effect graph using Win2D, or implementing the same effect using Direct2D directly. Although Direct2D sparsely documents the effect, it boils down to a simple multiplication of pixel values by a factor. Since you are dealing with color values of (1, 0, 0), (0, 1, 0) and (1, 0, 1), any multiplication by an amount greater than 1 will have no effect (color channel values above 1 are not preserved).

You might try to emulate the Photoshop Express behavior using the more flexible GammaTransfer effect, though you'll have to figure out the right factors for your scenario. Good luck!

**Comment by juanpaexpedite** [comment]
Well ok thank you, I was able to create my own Win2D shader successfully, but you know in theory is better use Composition when want to apply to several UIElements. 

Hope in the future let's have more flexibility, who knows even apply shaders in Composition :). Thank you again
