### ISSUE TITLE
See-through/transparent window container

### ISSUE THREAD

**Issue by v95** [Microsoft/WindowsUIDevLabs#90]
Hello,

I was wondering if the team has any plans to allow see-through/transparent app containers that can be used to achieve the "Aero" effect. I ask because allowing such styling could drastically improve designs for existing/upcoming apps. For example, take a look at [this concept image](http://orig12.deviantart.net/dcd4/f/2015/067/5/6/windows_10___dark_theme_by_metroversal-d8iwiqj.png) for a potential Windows 10 app. The Aero-like see-through blur on the left side makes the app look much better.

Thanks,
Saurabh

**Comment by tomzorz** [comment]
In addition to +1'ing this question I also want to follow it up with something a bit related.

The things I'd like to see:

- borderless (although we can kind-of pull this off with the title-bar modification)
- topmost window
- controlling window position

And some things that may or may not be in your "jurisdiction" :)

- ability to show/hide window in the taskbar
- taskbar toolbars (like what WMP mini player could do)
- tray icons, and advanced features on it - eg. I want to implement this without any winforms and other ugly hacking https://github.com/tomzorz/GestureReminder (check gif on page)

**Comment by juanpaexpedite** [comment]
Well there is also a not really too much relative UI but really important.
If you want to create a multiwindow app the viewmodels (datacontext property) is hardly impossible to share one among multiple windows, and explodes everywhere with dispatchers (you cannot go to the dispatcher of another window). That would be great to solve this, more info https://mtaulty.com/2015/09/16/m_15940/ I also lost a day trying to implement a solution by myself but there's no way. and because there is no a Windows team about this I do not know where to ask about this.

**Comment by pgills** [comment]
Thanks for the feedback. 

@v95 Currently, when you use a `CompositionBackdropBrush` it will only be applicable to the content within an application's window. Which means you can create blurred out panels within a application window, but not on the window itself.

@tomzorz, @juanpaexpedite Most of those requests are out of our teams scope, however I highly recommend submitting feedback like this via the Windows Insider Feedback Hub as typically gets routed pretty well to the right teams.

**Comment by juanpaexpedite** [comment]
Thank you, I already did it, feedback-hub:?contextid=380&feedbackid=b03b18a2-b955-49ba-9754-c30d677b3f88&form=1&src=2 hope one day this gets solved because imho it is a core feature.

**Comment by msftdavid** [comment]
Closing this feedback issue as it has been filed in the feedback hub per suggestion.
