### ISSUE TITLE
BackDrop scalability

### ISSUE THREAD

**Issue by ericgrover** [Microsoft/WindowsUIDevLabs#92]
I just added the new BackDrop control to a twitter client I am building.  I wanted the panel background of each tweet to have the glass effect.  I am loading 100 tweets (i.e. instances of BackDrop control) into a wrap grid.  It takes about 1 second for the visuals to get added to the visual tree (without the BackDrop control), and about 20 sec for the BackDrop controls to render.  

Is this the performance we should expect for these kind of effects, or is this something that can be improved?

**Comment by ratishphilip** [comment]
@ericgrover 
Just a doubt...Are you creating a backdrop brush within each of the BackDrop controls? If yes, could you try creating a common backdropbrush and sharing it with all the instances of your BackDrop control?

Does that improve the performance?

**Comment by JasterAtMicrosoft** [comment]
In addition to Ratish's suggestion, I would strongly recommend using a ListView or GridView with an ItemTemplate to display the tweets rather than adding controls to a WrapGrid. ListView and GridView implement UI virtualization so that only the UI elements needed to visualize the data in view will be instantiated, which should be less than the 100 tweets in the collection. The [XamlListView](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlListView) sample has several examples of using these controls to display data in a performant way.

**Comment by ericgrover** [comment]
Yes, I was.  I refactored it to share a brush and it totally solved my problem.  It is rendering really fast now.  Thanks!

**Comment by ericgrover** [comment]
Thanks for the suggestion.  I am actually not using an out of the box WrapGrid.  I created my own custom WrapGrid that does a different kind of layout.  The stock collection views don’t give me what I want.  I am going to try and implement virtualization in it eventually.
