### ISSUE TITLE
Scaling the DropShadow (without the blur)

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#93]
Finally I have installed the VS with the 14332 SDK in another machine and can test the new capabilities (I cannot debug because a weird error new instance but well, at least I can deploy).

In my case it would be great having an option **Scale** the **DropShadow** class, might be is possible doing a Transform2D but I will like not to do that. I want to create outlines in text as much big as I need.

Thank you

**Comment by sohchatt** [comment]
While the DropShadow class does not have a Scale property, you can achieve the same effect by associating your textVisual with a SpriteVisual (with no brush) of the same size, adding a DropShadow, and scaling this SpriteVisual (shadowVisual in the example below). I'm assuming that you're getting the Visual from a XAML TextBlock, but this technique should work generally for any case where you want to transform a DropShadow by leveraging the properties of the SpriteVisual that it is associated with:

            //get the textblock's visual and interop compositor
            var textVisual = ElementCompositionPreview.GetElementVisual(MyText);
            var compositor = textVisual.Compositor;

            //create a spritevisual and associate it with textVisual
            var shadowVisual = compositor.CreateSpriteVisual();
            shadowVisual .Size = MyText.RenderSize.ToVector2();

            //create a dropShadow with the text's alphamask and assign it to shadowVisual
            var shadow = compositor.CreateDropShadow();
            shadow.Mask = MyText.GetAlphaMask();
            shadowVisual .Shadow = shadow;

            //parent shadowVisual correctly in my XAML tree so it appears below MyText
            ElementCompositionPreview.SetElementChildVisual(MyTextShadowElement, shadowVisual );
            
This should give you the following result:

![scalableshadows1](https://cloud.githubusercontent.com/assets/16312588/15565490/ed96c23e-22cf-11e6-9b57-19a068aef735.jpg)


Now, to scale the shadow all you need to do is scale the shadowVisual we associated it with:
    
```
            //scale the visual about its center by 1.3x
            shadowVisual.CenterPoint = new Vector3(shadowSprite.Size / 2, 0);
            shadowVisual.Scale = new Vector3(1.3f, 1.3f, 0);`
```

And this should result in what I am hoping is your desired outcome:

![scalableshadows2](https://cloud.githubusercontent.com/assets/16312588/15565633/e20e4b52-22d0-11e6-941f-bf0e6830015c.jpg)

Note that when using ElementCompositionPreview.SetElementChild(), SpriteVisuals are drawn on top of their UIElement parent, so I needed to insert a hosting UIElement parent to the TextBlock (MyTextShadowElement in this example) so that the shadow would appear beneath the text.

If you now want the shadow's Scale to be coupled to properties of your textVisual (for the purpose of animations and so on), you can do so by using expression animations that relate shadowVisual to textVisual. 

I hope this helps!

**Comment by juanpaexpedite** [comment]
First thank you for the great explanation now I understand how it gets to work with the shadow with UIElement.

About the scaling, might be I should have used another name, might be dilate. 

I did several time ago some experiments with Win2D http://expediteapps.com/blog/more-texteffects-in-win2d/ based on MorphologyEffect and ArithmeticCompositeEffect.
 
I do not know how it is internally the Shadow created but that kind of stuff I did in my post is what I would to achieve,(overall the dilate of the MorphologyEffect).

![Image of dilate Win2d](http://expediteapps.com/blog/wp-content/uploads/2015/04/dilate.png)

Might be in the future get implemented these Win2D effects to Composition and apply them by my own.

I consider the explanation is enough to close this question, hope in the future having more effects and thank you as always for the effort to have time to answer us.
